### ISSUE TITLE
BUG: module 'pandas.io.formats' has no attribute 'html' --in version 1.3.4

### ISSUE THREAD

**Issue by vemaparna** [pandas-dev/pandas#45413]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame(data) # data is a dict
df
reads the df but not displayed
results in error as below:
module 'pandas.io.formats' has no attribute 'html'

the same command with same data works fine in my laptop with pandas 1.2.5
```

### Issue Description

module 'pandas.io.formats' has no attribute 'html'

### Expected Behavior

df = pd.DataFrame(data)
df
expected to return a dataframe showing the columns and rows

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.8.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-91-generic
Version          : #102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_IN
LOCALE           : en_IN.ISO8859-1

pandas           : 1.3.4
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 60.2.0
Cython           : 0.29.26
pytest           : 6.2.5
hypothesis       : 6.34.1
sphinx           : 4.3.2
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.30.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fsspec           : 2021.11.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.4.29
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.20.2
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.54.1

**Comment by phofl** [comment]
Does this work on 1.3.5?

**Comment by vemaparna** [comment]
Figured out that the error is due to inconsistencies in pandas versions installed in conda and pip. Error message vanishes, after uninstalling and reinstalling the updated version 1.3.5  in both. 

Thank you
