### PR TITLE
BUG/TST: ensure groupby.agg preserves extension dtype

### LINKED ISSUE #29141: BUG: regression on master in groupby agg with ExtensionArray
Example that I could make with DecimalArray:

```
In [1]: from pandas.tests.extension.decimal import DecimalArray, make_data 

In [2]: df = pd.DataFrame({'id': [0,0,0,1,1], 'decimals': DecimalArray(make_data()[:5])}) 

In [3]: df.groupby('id')['decimals'].agg(lambda x: x.iloc[0]) 
Out[8]: 
id
0      0.831922765262135044395108707249164581298828125
1    0.40839445887803604851029604105860926210880279...
dtype: object
```

On master of a few days ago, the above returned 'decimal' dtype instead of object dtype.

Found this in the geopandas test suite, as there it creates invalid output and then an error in a follow-up operation (https://travis-ci.org/geopandas/geopandas/jobs/600859374)

This seems to be caused by https://github.com/pandas-dev/pandas/pull/29088, and specifically the change in `agg_series`: https://github.com/pandas-dev/pandas/pull/29088/files#diff-8c0985a9fca770c2028bed688dfc043fR653-R666 
The `self._aggregate_series_fast` is giving a "AttributeError: 'DecimalArray' object has no attribute 'flags'" error if the series is backed by an EA, and the AttributeError is no longer catched.

cc @jbrockmendel

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Closes https://github.com/pandas-dev/pandas/issues/29141

@jbrockmendel this is adding the cases I found in https://github.com/pandas-dev/pandas/issues/29141. It does a small revert of catching an error to get them passing, but then your PR can fix it properly?

### CODE REVIEW

File: pandas/core/groupby/ops.py [hunk 1]
```diff
@@ -655,15 +655,15 @@ def agg_series(self, obj, func):
             return self._aggregate_series_fast(obj, func)
         except AssertionError:
             raise
-        except ValueError as err:
+        except (ValueError, AttributeError) as err:
```
Comment (jreback) [inline pandas/core/groupby/ops.py]: what is the AttributeError in reference?

**Review by jreback — CHANGES_REQUESTED** [review]

File: pandas/core/groupby/ops.py (hunk 1 above)
Comment (jorisvandenbossche) [reply pandas/core/groupby/ops.py]: See the issue https://github.com/pandas-dev/pandas/issues/29141. Now, since https://github.com/pandas-dev/pandas/pull/29100 is already merged, the AttributeError might not be needed anymore for our tests to pass.

File: pandas/core/groupby/ops.py [hunk 2]
```diff
@@ -655,15 +655,15 @@ def agg_series(self, obj, func):
...
+        except (ValueError, AttributeError, TypeError) as err:
             if "No result." in str(err):
                 # raised in libreduction
                 pass
             elif "Function does not reduce" in str(err):
                 # raised in libreduction
                 pass
             else:
-                raise
+                pass
```
Comment (jorisvandenbossche) [inline pandas/core/groupby/ops.py]: @jbrockmendel the whole block is now basically an `except (..): pass` (so I could make it much shorter), but you might have put in those specific checks as pointers to what to clean up later?

File: pandas/core/groupby/ops.py (hunk 1 above)
Comment (jorisvandenbossche) [reply pandas/core/groupby/ops.py]: It only solves the fact that an AttributeError needs to be catched (I removed that in the last commit), it does not make the tests pass (as I mentioned yesterday)

File: pandas/core/groupby/ops.py (hunk 2 above)
Comment (jbrockmendel) [reply pandas/core/groupby/ops.py]: so something is being done with a DecimalArray that raises a TypeError?  and i guess by not-catching it here it is getting caught somewhere above that isn't doing re-casting appropriately?  can we track down where that is?

Comment (jbrockmendel) [reply pandas/core/groupby/ops.py]: It looks like in _aggregate_series_fast there is a call to libreduction that tries to assign this DecimalArray to a name that libreduction has typed as an ndarray, which raises TypeError

Comment (jorisvandenbossche) [reply pandas/core/groupby/ops.py]: But that is expected I think?

Comment (jbrockmendel) [reply pandas/core/groupby/ops.py]: we get to decide what is "expected"; maybe i dont understand what you're getting at

Comment (jorisvandenbossche) [reply pandas/core/groupby/ops.py]: Well, we try the fast path, and if that fails, we go for the slow path. So here it fails, so we choose the slow path. That is how I understand that it is currently designed.

Comment (jbrockmendel) [reply pandas/core/groupby/ops.py]: so if we fix the issue in libreduction, there's a chance that the fast path will work

Comment (jorisvandenbossche) [reply pandas/core/groupby/ops.py]: libreduction is not meant to work for all cases, eg if the values is not an ndarray. Yes, we could handle that differently (eg check in advance if it should work), but that is not the approach that is currently taken. I would prefer to limit the scope of this PR to adding the test cases and restoring the old behaviour with a minimal change.

Comment (jbrockmendel) [reply pandas/core/groupby/ops.py]: OK, how about add the test and xfail it.  i'll get to it shortly

Comment (jorisvandenbossche) [reply pandas/core/groupby/ops.py]: If you'll get to it shortly, how about merging this (with further edits based on feedback of course), and at least fixing the regression on master?

File: pandas/core/groupby/ops.py [hunk 3]
```diff
@@ -655,15 +655,15 @@ def agg_series(self, obj, func):
             return self._aggregate_series_fast(obj, func)
         except AssertionError:
             raise
-        except ValueError as err:
+        except (ValueError, TypeError) as err:
             if "No result." in str(err):
                 # raised in libreduction
                 pass
             elif "Function does not reduce" in str(err):
                 # raised in libreduction
```
Comment (jorisvandenbossche) [inline pandas/core/groupby/ops.py]: @jbrockmendel is it the intention to keep this long term, or is this also planned to be cleaned-up in a follow-up?

File: pandas/core/groupby/ops.py (hunk 2 above)
Comment (jorisvandenbossche) [reply pandas/core/groupby/ops.py]: To clarify: I would personally prefer to merge this without xfail to have the coverage on master. You're doing other PRs cleaning things up in groupby, and it would be good to ensure this keeps working

File: pandas/core/groupby/ops.py (hunk 3 above)
Comment (jbrockmendel) [reply pandas/core/groupby/ops.py]: cleaned

File: pandas/core/groupby/ops.py (hunk 2 above)
Comment (jbrockmendel) [reply pandas/core/groupby/ops.py]: fair enough

Comment (jbrockmendel) [reply pandas/core/groupby/ops.py]: actually, can you do the same `str(err)` checking so that we only let through the relevant TypeErrors?  One of the other PRs afoot is specifically targeting other TypeErrors

Comment (jorisvandenbossche) [reply pandas/core/groupby/ops.py]: That's an error message coming from another library though (cython?). Do we have guarantee that that is stable? 
(the other two errors that are catched that way are raised by our own code in reduction.pyx)

File: pandas/core/groupby/ops.py (hunk 3 above)
Comment (jorisvandenbossche) [reply pandas/core/groupby/ops.py]: And what's the idea of how to clean this up? 
(we could also raise a more specific internal error (subclass) to catch)

File: pandas/core/groupby/ops.py (hunk 2 above)
Comment (jbrockmendel) [reply pandas/core/groupby/ops.py]: > Do we have guarantee that that is stable?

If nothing else, you can check that both "ndarray" and "DecimalArray" are present.  I'm sure you can figure something out.

File: pandas/core/groupby/ops.py (hunk 3 above)
Comment (jbrockmendel) [reply pandas/core/groupby/ops.py]: > (we could also raise a more specific internal error (subclass) to catch)

That's what I'm leaning towards, yah

File: pandas/core/groupby/ops.py (hunk 2 above)
Comment (jorisvandenbossche) [reply pandas/core/groupby/ops.py]: This is not only for DecimalArray, but for any kind of internal/external EA.

Comment (jorisvandenbossche) [reply pandas/core/groupby/ops.py]: But can add the check for just ndarray.

**Comment by WillAyd** [comment]
Hmm so I think I'm a little hesitant to merge this one. Didn't follow all of the back and forth but do we know a general purpose solution is?

These Exception cleanups are extremely valuable; as evidenced by this PR the amount of catching of re-wiring that goes on is impossible to reason about, so putting this back in might have subtle side effects we don't know about.

**Comment by jbrockmendel** [comment]
> so putting this back in might have subtle side effects we don't know about.

FWIW ive copied the test this introduces into a local branch and am figuring out what "the right" way to do this is.  #29103 is a blocker for that I'm pretty sure

**Comment by jorisvandenbossche** [comment]
> Hmm so I think I'm a little hesitant to merge this one.  Didn't follow all of the back and forth but do we know a general purpose  solution is?

Well, until three days ago, this *was* the solution; so it can't be that bad (and the "subtle side effects we don't know about" are then the ones we have had for years ..). Yes, those clean-ups are valuable, I don't disagree with that, but all I propose is to figure out the better solution while master is restored to the previous behaviour, and while we have tests in place to guarantee the behaviour (also for other open PRs).

Further, I actually think this can be a good solution. The TypeError is fully expected if a non-ndarray is passed into the fastpath. For sure, we can also check that in advance, and then don't pass it in. But both are valid python idioms.

**Comment by jbrockmendel** [comment]
@jorisvandenbossche i've got a local branch about ready that copy/pastes the tests from this PR and implements a longer-term fix.  does the Decimal test here sufficiently cover the Geopandas breakage you mentioned before?

**Comment by jorisvandenbossche** [comment]
@jbrockmendel OK, that sounds good. Then will merge this PR and you can remove the catched typeerror again in your upcoming PR.

> does the Decimal test here sufficiently cover the Geopandas breakage you mentioned before?

I *hope*, but it's difficult to be sure :), as it is a quite different EA. In any case, with the change I did that fixed the decimal test, also fixed my geopandas test, so they seem quite related. And I added the test with a custom decimal method to mimic it a bit more.

**Comment by WillAyd** [comment]
This wasn't approved by anyone - why merge this instead of helping @jbrockmendel ?

**Comment by jorisvandenbossche** [comment]
As I mentioned before, to have tests in place to ensure Brock's PRs pass them (there are several open PRs that touch the groupby code, not just a single one). In the discussion above, I didn't hear any objection to the tests itself, so assumed the tests itself were OK.

**Comment by jorisvandenbossche** [comment]
To come back to this a final time: Will, you are right, I shouldn't have merged before asking again given the discussion. Sorry about that. I was a bit frustrated with the discussion, but I should not have let my frustration ignore the discussion.
