### PR TITLE
feat!: Removes `inplace` option for `pandas.core.resample.Resampler.i…

### LINKED ISSUE #58690: BUG: In `main`, using `resample().interpolate(inplace=True)` raises an exception
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import numpy as np
from pandas import date_range, DataFrame
DR = date_range("1999-1-1", periods=365, freq="D")
DF_ = DataFrame(np.random.standard_normal((365, 1)), index=DR)
S = DF_.iloc[:, 0]
DF = DataFrame({"col1": S, "col2": S})

DF.resample("ME").interpolate(inplace=True)
```

### Issue Description

Code raises an exception:
```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\pandasstubs\lib\site-packages\pandas\core\resample.py", line 958, in interpolate
    result_interpolated = result_interpolated.loc[final_index]
AttributeError: 'NoneType' object has no attribute 'loc'
```

### Expected Behavior

No exception.  Works fine in pandas 2.2.2

Note:  Seems to be introduced by https://github.com/pandas-dev/pandas/pull/56515 by @cbpygit , review by @MarcoGorelli and @jbrockmendel 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 34177d6b20896bf101590306e3f0e1e0a225c5fb
python                : 3.9.16.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_United States.1252

pandas                : 3.0.0.dev0+943.g34177d6b20
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 68.2.2
pip                   : 22.3.1
Cython                : None
pytest                : 8.2.0
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : 3.2.0
lxml.etree            : 5.2.1
html5lib              : 1.1
pymysql               : None
psycopg2              : None
jinja2                : 3.1.4
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.4
numba                 : None
numexpr               : 2.10.0
odfpy                 : None
openpyxl              : 3.1.2
pyarrow               : 16.0.0
pyreadstat            : 1.2.7
python-calamine       : None
pyxlsb                : 1.0.10
s3fs                  : None
scipy                 : 1.13.0
sqlalchemy            : 2.0.30
tables                : 3.9.2
tabulate              : 0.9.0
xarray                : 2024.3.0
xlrd                  : 2.0.1
zstandard             : 0.22.0
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

### PR DESCRIPTION
**Pull request by cbpygit**
…nterpolate`. Fixes / cleans up related test cases.

- [x] closes #58690 (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by cbpygit** [comment]
@MarcoGorelli somehow it did not auto-assign the reviewers. But in any case, here we are :)

**Comment by Aloqeely** [comment]
Do these need to be deprecated first? You can use the `deprecate_kwarg` decorator for that

**Comment by cbpygit** [comment]
> Do these need to be deprecated first? You can use the `deprecate_kwarg` decorator for that

I don't know what the exact policy is. But as far as I understand the deprecation tells the user that a certain **future** change will change the API. This does not apply here, as the inplace-functionality is already broken. We would need to add the deprecation to pandas 2 to inform users about the upcoming change, and to ease migration. But I guess this would need a separate PR that targets the next 2.x release.

**Comment by MarcoGorelli** [comment]
> Do these need to be deprecated first?

Thanks @Aloqeely - in general, yes, this would require a deprecation. However, here, the change is going to breaking anyway (in order to fix a historic ~~feature~~ bug), so to be honest I'd be OK removing `inplace` without warning too

File: pandas/core/resample.py [hunk 1]
```diff
@@ -909,6 +906,8 @@ def interpolate(
         ``07:00:00`` and ``07:00:02``.
         """
         assert downcast is lib.no_default  # just checking coverage
+        if kwargs.get("inplace"):
```
Comment (mroeschke) [inline pandas/core/resample.py:909]: Could we disallow `inplace` without having a check here?

Comment (cbpygit) [reply pandas/core/resample.py:909]: Because it is passed twice you mean, I see. But this will not produce a useful error message for the user, will it? I still don't know what you have in mind, would be awesome if you could propose a precise improvement 🙏

File: pandas/tests/copy_view/test_interp_fillna.py [hunk 2]
```diff
@@ -132,7 +132,7 @@ def test_interpolate_object_convert_copies():
     arr_a = get_array(df, "a")
     msg = "Can not interpolate with method=pad"
     with pytest.raises(ValueError, match=msg):
-        df.interpolate(method="pad", inplace=True, downcast="infer")
+        df.interpolate(method="pad", inplace=False, downcast="infer")
```
Comment (mroeschke) [inline pandas/tests/copy_view/test_interp_fillna.py:135]: From the original issue, I think we only wanted to disallow `inplace` for `resample.interpolate`?

Comment (cbpygit) [reply pandas/tests/copy_view/test_interp_fillna.py:135]: Pretty sure the test was failing 🤔 But I can check it again!

Comment (cbpygit) [reply pandas/tests/copy_view/test_interp_fillna.py]: You are right @mroeschke, it was a Find&Replace mistake. Revert and works.

File: pandas/tests/copy_view/test_interp_fillna.py [hunk 3]
```diff
@@ -146,7 +146,7 @@ def test_interpolate_downcast_reference_triggers_copy():
 
     msg = "Can not interpolate with method=pad"
     with pytest.raises(ValueError, match=msg):
-        df.interpolate(method="pad", inplace=True, downcast="infer")
```
Comment (mroeschke) [inline pandas/tests/copy_view/test_interp_fillna.py:149]: It appears that a lot of interpolate usages are still modified in the PR. _Only_ tests that used to call`.resample(...).interpolate(interpolate=)` should have been changed

**Review by mroeschke — CHANGES_REQUESTED** [review]

**Comment by cbpygit** [comment]
> This pull request is stale because it has been open for thirty days with no activity. Please [update](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#updating-your-pull-request) and respond to this comment if you're still interested in working on this.

I'll work on this, I was just unable to spend time.

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.
