### PR TITLE
TST: astyp via loc to int64

### LINKED ISSUE #31861: Assigned conversion via loc to Int64 fails under peculiar conditions
#### Code Sample, a copy-pastable example if possible

```python
test = pd.DataFrame({'a': ['test'], 'b': [np.nan]})
test.loc[:, 'b'] = test.loc[:, 'b'].astype('Int64')
# *** AttributeError: 'IntegerArray' object has no attribute 'size'
```
#### Problem description

Assignment of `.astype('Int64')` sometimes fails with `AttributeError: 'IntegerArray' object has no attribute 'size'`.

Initially, I thought this was a regression from #25584, but it only manifests under very specific conditions:

1. There is exactly one null value in the converted column
    ```python
    # works
    test = pd.DataFrame({'a': ['test', 'test'], 'b': [np.nan, 1.0]})
    test.loc[:, 'b'] = test.loc[:, 'b'].astype('Int64')

    # works
    test = pd.DataFrame({'a': ['test', 'test'], 'b': [np.nan, np.nan]})
    test.loc[:, 'b'] = test.loc[:, 'b'].astype('Int64')

    # fails
    test = pd.DataFrame({'a': ['test'], 'b': [np.nan]})
    test.loc[:, 'b'] = test.loc[:, 'b'].astype('Int64')
    # *** AttributeError: 'IntegerArray' object has no attribute 'size'
    ```
2. There is another column in the DataFrame
    ```python
    # works
    test = pd.DataFrame({'b': [np.nan]})
    test.loc[:, 'b'] = test.loc[:, 'b'].astype('Int64')
    ```
3. Assignment happens via `df.loc[:, colname]` - without assignment, or with assignment to `df[colname]`, things work.
    ```python
    test = pd.DataFrame({'a': ['test'], 'b': [np.nan]})

    # fails
    test.loc[:, 'b'] = test['b'].astype('Int64')
    # *** AttributeError: 'IntegerArray' object has no attribute 'size'

    # fails
    test.loc[:, 'b'] = test.loc[:, 'b'].astype('Int64')
    # *** AttributeError: 'IntegerArray' object has no attribute 'size'

    # works
    test.loc[:, 'b'].astype('Int64')

    # works
    test['b'] = test['b'].astype('Int64')
    ```

#### Expected Output

`test.loc[:, 'b'] = test.loc[:, 'b'].astype('Int64')` shouldn't raise an `AttributeError`. 

`print(test)` after assignment should read along the lines of

```
0    <NA>
dtype: Int64
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-46-generic
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.1
numpy            : 1.16.1
pytz             : 2018.9
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.4.0
Cython           : None
pytest           : 3.10.1
hypothesis       : None
sphinx           : 1.8.5
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.3.0
html5lib         : None
pymysql          : 0.9.3
psycopg2         : None
jinja2           : 2.10
IPython          : 7.2.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.0
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 3.10.1
pyxlsb           : None
s3fs             : None
scipy            : 1.2.0
sqlalchemy       : 1.2.17
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

### PR DESCRIPTION
**Pull request by hardikpnsp**
- [x] closes #31861
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Adds a test for a special case of `astype` via `loc` to extension type Int64 when data has np.nan or pd.NA.

### CODE REVIEW

**Review by arw2019 — CHANGES_REQUESTED** [review]
Thanks @hardikpnsp for the PR! 

Looks good! Some small comments

File: pandas/tests/frame/methods/test_astype.py [hunk 1]
```diff
@@ -136,6 +137,15 @@ def test_astype_cast_nan_inf_int(self, val, dtype):
         with pytest.raises(ValueError, match=msg):
             df.astype(dtype)
 
+    @pytest.mark.parametrize("dtype", ["Int64", "Int32", "Int16"])
+    @pytest.mark.parametrize("val", [np.nan, NA])
+    def test_astype_cast_via_loc_nan_int(self, val, dtype):
+        # see GH#31861
+        expected = DataFrame({"a": ["foo"], "b": integer_array([val], dtype=dtype)})
+        result = DataFrame({"a": ["foo"], "b": [val]})
```
[the remark this answers is not in the document]
Comment (hardikpnsp) [reply pandas/tests/frame/methods/test_astype.py:145]: Thanks for the input! I agree, its better to call it `df`, I will try to quickly fix these.

**Review by arw2019 — APPROVED** [review]

File: pandas/tests/frame/methods/test_astype.py [hunk 2]
```diff
@@ -136,6 +137,15 @@ def test_astype_cast_nan_inf_int(self, val, dtype):
         with pytest.raises(ValueError, match=msg):
             df.astype(dtype)
 
+    @pytest.mark.parametrize("dtype", ["Int64", "Int32", "Int16"])
+    @pytest.mark.parametrize("val", [np.nan, NA])
+    def test_astype_cast_via_loc_nan_int(self, val, dtype):
+        # GH31861
```
Comment (jreback) [inline pandas/tests/frame/methods/test_astype.py:143]: can you add the working conditions as well (e.g. nan + a value) from the OP

File: pandas/tests/frame/methods/test_astype.py [hunk 3]
```diff
@@ -136,6 +137,15 @@ def test_astype_cast_nan_inf_int(self, val, dtype):
         with pytest.raises(ValueError, match=msg):
             df.astype(dtype)
 
+    @pytest.mark.parametrize("dtype", ["Int64", "Int32", "Int16"])
+    @pytest.mark.parametrize("val", [np.nan, NA])
```
Comment (jreback) [inline pandas/tests/frame/methods/test_astype.py:141]: use `nulls_fixture` instead and `any_nullable_int_dtype` fixture

**Review by jreback — CHANGES_REQUESTED** [review]

File: pandas/tests/frame/methods/test_astype.py (hunk 2 above)
Comment (hardikpnsp) [reply pandas/tests/frame/methods/test_astype.py:143]: sure! let me try.

File: pandas/tests/frame/methods/test_astype.py (hunk 3 above)
Comment (hardikpnsp) [reply pandas/tests/frame/methods/test_astype.py:141]: Hey, here in `nulls_fixture`, the test case fails for `pd.NaT` because it is inferred as `datetime64`. I think it is expected behavior but would like your opinion on it.

code snippet for reference
```python
>>> df = pd.DataFrame({"a": ["foo"], "b": [pd.NaT]})
>>> df.dtypes
a            object
b    datetime64[ns]
dtype: object
>>> df.loc[:, "b"] = df.loc[:, "b"].astype('Int64')
TypeError: datetime64[ns] cannot be converted to an IntegerDtype
```

Comment (hardikpnsp) [reply pandas/tests/frame/methods/test_astype.py:141]: @arw2019  @jreback , Any updates on this one? would appreciate some help and direction.

Comment (arw2019) [reply pandas/tests/frame/methods/test_astype.py:141]: Could use `pytest.skipif` for the datetime case
or test for the `TypeError` somehow but I'm not sure that's necessary

**Review by arw2019 — COMMENTED** [review]
Sorry @hardikpnsp for being quiet

Responded to the question below. If you feel like reopening and pushing the changes to parameterization (use fixtures as suggested) this should be good to go in
