### PR TITLE
BUG: Fix #25959 - Don't call .array in DatetimeLikeArrayMixin's map

### LINKED ISSUE #25959: Series.apply fails when the series is a timezone aware datetime
To reproduce the problem:
```python
import pandas as pd

s = pd.util.testing.makeTimeSeries()
s = s.tz_localize('UTC')
pd.Series(s.index).apply(lambda x: pd.Series([1,2]))

AttributeError: 'PandasArray' object has no attribute 'tolist'
```
It works fine if the function to apply returns a scalar instead of a Series:

```python
import pandas as pd

s = pd.util.testing.makeTimeSeries()
s = s.tz_localize('UTC')
pd.Series(s.index).apply(lambda x: 1)
```
or it there is no timezone information in the series.
```python
import pandas as pd

s = pd.util.testing.makeTimeSeries()
pd.Series(s.index).apply(lambda x: pd.Series([1,2]))
```
The issue is present with pandas 0.24.2, it used to work fine with 0.23.4.

### PR DESCRIPTION
**Pull request by ThomasKluiters**
- [x] closes #25959
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

In Series.apply we call .array on returning the result of DatetimeLikeArrayMixin map, which causes an error.

### CODE REVIEW

File: pandas/tests/indexes/datetimes/test_datetime.py [hunk 1]
```diff
@@ -433,3 +433,10 @@ def test_asarray_tz_aware(self):
             result = np.asarray(idx, dtype=object)
 
         tm.assert_numpy_array_equal(result, expected)
+
+    def test_apply_on_series(self):
```
Comment (mroeschke) [inline pandas/tests/indexes/datetimes/test_datetime.py]: 1) Could you move this test where the other timezone related tests are?

2) Test should compare a `result` output and `expected` output. In this particular case. You'll want to create 2 series and use `tm.assert_series_equal` to compare the 2.

File: pandas/core/arrays/datetimelike.py [hunk 2]
```diff
@@ -713,7 +713,7 @@ def map(self, mapper):
         # Else, just rewrite _map_infer_values to do the right thing.
         from pandas import Index
 
-        return Index(self).map(mapper).array
+        return Index(self).map(mapper)
```
Comment (mroeschke) [inline pandas/core/arrays/datetimelike.py]: I suspect this isn't the fix that we would want although test are passing. We want ExtensionArrays methods to return ExtensionArrays and not Indexes. Could you investigate another fix (maybe in apply?)

**Review by mroeschke — CHANGES_REQUESTED** [review]
Some comments and also needs a whatsnew entry in 0.25

File: pandas/tests/indexes/datetimes/test_datetime.py (hunk 1 above)
Comment (ThomasKluiters) [reply pandas/tests/indexes/datetimes/test_datetime.py]: Thanks for the feedback, I'll get right on it :)

File: pandas/core/arrays/datetimelike.py (hunk 2 above)
Comment (gfyoung) [reply pandas/core/arrays/datetimelike.py]: cc @jbrockmendel , as there was further discussion in the issue regarding a proper patch

Comment (ThomasKluiters) [reply pandas/core/arrays/datetimelike.py]: I've reverted my changes and move the fix down to apply

File: pandas/tests/indexes/datetimes/test_datetime.py (hunk 1 above)
Comment (ThomasKluiters) [reply pandas/tests/indexes/datetimes/test_datetime.py]: I've moved the test to the "test_datetime_index" test file.

In this case I made use of assert_frame_equal as the issue is the fact that apply fails on Series that have a DateTimeIndex, and a DataFrame is not returned as expected.

**Comment by ThomasKluiters** [comment]
> Some comments and also needs a whatsnew entry in 0.25

Added!

File: pandas/tests/resample/test_datetime_index.py [hunk 3]
```diff
@@ -1488,3 +1488,13 @@ def test_get_timestamp_range_edges(first, last, offset,
     result = _get_timestamp_range_edges(first, last, offset)
     expected = (exp_first, exp_last)
     assert result == expected
+
+
```
Comment (jreback) [inline pandas/tests/resample/test_datetime_index.py]: this needs to go in pandas/tests/series/test_apply.py

File: doc/source/whatsnew/v0.25.0.rst [hunk 4]
```diff
@@ -283,6 +283,7 @@ Timezones
 - Bug in :func:`Timestamp.tz_localize` and :func:`Timestamp.tz_convert` does not propagate ``freq`` (:issue:`25241`)
 - Bug in :func:`Series.at` where setting :class:`Timestamp` with timezone raises ``TypeError`` (:issue:`25506`)
 - Bug in :func:`DataFrame.update` when updating with timezone aware data would return timezone naive data (:issue:`25807`)
+- Bug in :func:`Series.apply` failed when the series is a timezone aware datetime index (:issue:`25959`)
```
Comment (jreback) [inline doc/source/whatsnew/v0.25.0.rst]: move to reshaping

instead of: timezone aware datetime index 
``timezone aware DatetimeIndex``, with double-backticks around DTI

File: pandas/tests/resample/test_datetime_index.py [hunk 5]
```diff
@@ -1488,3 +1488,13 @@ def test_get_timestamp_range_edges(first, last, offset,
...
+def test_apply_on_series():
+    # GH 25959
+    # Calling apply on a localized time series should not cause an error
```
Comment (jreback) [inline pandas/tests/resample/test_datetime_index.py]: pls parameterize over both the working and the originally non-working example in the OP

**Review by jreback — CHANGES_REQUESTED** [review]

File: doc/source/whatsnew/v0.25.0.rst [hunk 6]
```diff
@@ -387,6 +387,7 @@ Reshaping
 - Bug in :func:`concat` where order of ``OrderedDict`` (and ``dict`` in Python 3.6+) is not respected, when passed in as  ``objs`` argument (:issue:`21510`)
 - Bug in :func:`concat` where the resulting ``freq`` of two :class:`DatetimeIndex` with the same ``freq`` would be dropped (:issue:`3232`).
 - Bug in :func:`merge` where merging with equivalent Categorical dtypes was raising an error (:issue:`22501`)
+- Bug in :func:`Series.apply` failed when the series is a timezone aware :class:`DateTimeIndex` (:issue:`25959`)
```
Comment (mroeschke) [inline doc/source/whatsnew/v0.25.0.rst]: `DatetimeIndex` (lowercase t)

File: pandas/tests/resample/test_datetime_index.py (hunk 3 above)
Comment (ThomasKluiters) [reply pandas/tests/resample/test_datetime_index.py]: Fixed!

File: doc/source/whatsnew/v0.25.0.rst (hunk 4 above)
Comment (ThomasKluiters) [reply doc/source/whatsnew/v0.25.0.rst]: Fixed!

File: pandas/tests/resample/test_datetime_index.py (hunk 5 above)
Comment (ThomasKluiters) [reply pandas/tests/resample/test_datetime_index.py]: Fixed!

**Comment by ThomasKluiters** [comment]
I don't know why the tests are failing - locally all seems fine

**Comment by ThomasKluiters** [comment]
@jreback @mroeschke I resolved my issues, could you have a look please?

File: pandas/core/series.py [hunk 7]
```diff
@@ -3688,7 +3688,11 @@ def f(x):
 
         if len(mapped) and isinstance(mapped[0], Series):
             from pandas.core.frame import DataFrame
-            return DataFrame(mapped.tolist(), index=self.index)
+            # GH 25959 we don't need to call tolist
+            # if we've been given an ExtensionArray
+            if not isinstance(mapped, ExtensionArray):
```
Comment (TomAugspurger) [inline pandas/core/series.py]: Use is_extension_array_dtype(mapped.dtype)

Why do we call tolist in the first place?

Comment (ThomasKluiters) [reply pandas/core/series.py]: It was initially there - I do not know, I resolved your problem though.

**Comment by TomAugspurger** [comment]
Can you investigate what happens if we don’t cal tolist? What tests fail?

**Comment by TomAugspurger** [comment]
So are we using tolist to get an array from a series? Maybe call pd.array on the object instead of tolist?

**Comment by ThomasKluiters** [comment]
> So are we using tolist to get an array from a series? Maybe call pd.array on the object instead of tolist?

pd.array seems to be the best solution, it removes the need to check for an EA. Any suggestions on how I can fix the conflict best in the whatsnew?

**Comment by TomAugspurger** [comment]
Actually I think we have a better function than pd.array. It’s something like extract_array in internals.

**Comment by ThomasKluiters** [comment]
> extract_array

extract_array does not work I'm afraid, it will fail the same test

File: pandas/core/series.py [hunk 8]
```diff
@@ -3687,7 +3687,9 @@ def f(x):
 
         if len(mapped) and isinstance(mapped[0], Series):
             from pandas.core.frame import DataFrame
-            return DataFrame(mapped.tolist(), index=self.index)
+            # GH 25959 use pd.array instead of tolist
+            # so extension arrays can be used
```
Comment (TomAugspurger) [inline pandas/core/series.py]: Sorry,can mapped be 2d here? If so, we shouldn’t use pd.array

Comment (ThomasKluiters) [reply pandas/core/series.py]: Yes, it is possible for it to be a nested series.

**Comment by jreback** [comment]
can you merge master

**Comment by ThomasKluiters** [comment]
> can you merge master

Done!

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
can you merge master and ping on green.

**Comment by jreback** [comment]
you have an isort error; can you merge master and fix up. ping on green.

**Comment by ThomasKluiters** [comment]
> you have an isort error; can you merge master and fix up. ping on green.

Sorry, but I can't seem to find what's wrong with the build - it seems to be failing at /doc/source/reference/frame.rst - "DataFrame" has no attribute "to_panel".

**Comment by WillAyd** [comment]
Should be fixed after #26308

**Comment by jreback** [comment]
can you merge master

File: pandas/core/series.py [hunk 9]
```diff
@@ -3702,8 +3703,9 @@ def f(x):
                 mapped = lib.map_infer(values, f, convert=convert_dtype)
 
         if len(mapped) and isinstance(mapped[0], Series):
-            from pandas.core.frame import DataFrame
-            return DataFrame(mapped.tolist(), index=self.index)
+            # GH 25959 use pd.array instead of tolist
```
Comment (jreback) [inline pandas/core/series.py]: can you remove the pd from above, and instead  just use ``self._constructor_expanddim`` here

**Review by jreback — CHANGES_REQUESTED** [review]
small comments, ping on green.

**Comment by jreback** [comment]
linting error:

```
./pandas/core/series.py(3708,80): error E501: line too long (82 > 79 characters)
Bash exited with code '1'.
```

**Comment by jreback** [comment]
ping on green.

File: pandas/tests/series/test_apply.py [hunk 10]
```diff
@@ -671,3 +671,16 @@ def test_map_missing_mixed(self, vals, mapping, exp):
         result = s.map(mapping)
 
         tm.assert_series_equal(result, pd.Series(exp))
+
+    @pytest.mark.parametrize("dti,exp", [
+        (Series([1, 2], index=pd.DatetimeIndex([0, 31536000000])),
+            DataFrame(np.repeat([[1, 2]], 2, axis=0), dtype='int64')),
+        (tm.makeTimeSeries(nper=30),
+            DataFrame(np.repeat([[1, 2]], 30, axis=0), dtype='int64'))
```
Comment (jreback) [inline pandas/tests/series/test_apply.py]: I think there is a 3rd case listed in the OP (of which 2 works fine), can you add that one

**Review by jreback — CHANGES_REQUESTED** [review]

**Comment by ThomasKluiters** [comment]
@jreblack ping

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @ThomasKluiters
