### PR TITLE
BUG: GH12824 fixed apply() returns different result depending on whet…

### LINKED ISSUE #12824: groupby().apply() returns different result depends on the first result is None or not.
The apply document says that it can:

> apply can act as a reducer, transformer, or filter function, depending on exactly what is passed to apply. So depending on the path taken, and exactly what you are grouping. Thus the grouped columns(s) may be included in the output as well as set the indices. 

So, I think it may discard the group if the callback function returns None. Here is two exmaple that works and not works:

```
import pandas as pd
import numpy as np

df = pd.DataFrame({"A":np.arange(10), "B":[1, 1, 1, 2, 3, 3, 3, 4, 4, 4]})
print(df.groupby("B").apply(lambda df2:None if df2.shape[0] <= 2 else df2.iloc[[0, -1]]))

df = pd.DataFrame({"A":np.arange(10), "B":[1, 2, 2, 2, 3, 3, 3, 4, 4, 4]})
print(df.groupby("B").apply(lambda x:None if x.shape[0] <= 2 else x.iloc[[0, -1]]))
```

the output is as following, the first one returns a DataFrame, the second one returns a Series with DataFrames inside:

```
     A  B
B        
1 0  0  1
  2  2  1
3 4  4  3
  6  6  3
4 7  7  4
  9  9  4


B
1         A    B
1  NaN  NaN
3  NaN  NaN
2                   A  B
1  1  2
3  3  2
3                   A  B
4  4  3
6  6  3
4                   A  B
7  7  4
9  9  4
dtype: object
```

The problem is that `_wrap_applied_output()` in `groupby.py` checks the first element to determine the concat method:

```
    if isinstance(values[0], DataFrame):
        return self._concat_objects(keys, values,
                                    not_indexed_same=not_indexed_same)
```             

I want to know, does `groupby().apply()` support discarding groups?

### PR DESCRIPTION
**Pull request by adneu**
- [x] closes #12824 
- [x] tests added / passed
- [x] passes `git diff upstream/master | flake8 --diff`
- [x] whatsnew entry

In `_wrap_applied_output` for `NDFrameGroupBy`, if the first result of `apply` is `None`, find the first non-`None` result to determine behavior

### CODE REVIEW

File: pandas/core/groupby.py [hunk 1]
```diff
@@ -3210,7 +3210,15 @@ def _wrap_applied_output(self, keys, values, not_indexed_same=False):
 
         key_names = self.grouper.names
 
-        if isinstance(values[0], DataFrame):
+        # GH12824.
+        v = values[0]
+        if v is None:
```
Comment (jreback) [inline pandas/core/groupby.py]: make this a helper function in ``core/groupby.py`` (and consolidate the other one which has the same code)

File: pandas/tests/test_groupby.py [hunk 2]
```diff
@@ -6216,6 +6216,19 @@ def test_func(x):
...
+        test_df = DataFrame({'groups': [0, 1, 1, 1],
+                             'vars': [8, 7, 4, 5]})
+
+        def test_func(x):
+            if x.shape[0] < 2:
+                return None
+            return x.iloc[[0, -1]]
+
+        result = test_df.groupby('groups').apply(test_func)
+        tm.assertIsInstance(result, DataFrame)
```
Comment (jreback) [inline pandas/tests/test_groupby.py]: construct the expected return frame and use ``assert_frame_equal``

**Comment by jreback** [comment]
can you rebase / update

**Comment by adneu** [comment]
Rebased and made the changes you suggested but there was a new error with the test. It is introduced by #12743 which now throws an error in `_concat_objects` when any of the values are `None` (see below). The new PR makes a small change to deal with this, can you check if ok?

```
======================================================================
ERROR: test_groupby_apply_none_first (pandas.tests.test_groupby.TestGroupBy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../pandas/tests/test_groupby.py", line 6292, in test_groupby_apply_none_first
    result = test_df.groupby('groups').apply(test_func)
  File ".../pandas/core/groupby.py", line 651, in apply
    return self._python_apply_general(f)
  File ".../pandas/core/groupby.py", line 660, in _python_apply_general
    not_indexed_same=mutated or self.mutated)
  File ".../pandas/core/groupby.py", line 3241, in _wrap_applied_output
    not_indexed_same=not_indexed_same)
  File ".../pandas/core/groupby.py", line 824, in _concat_objects
    values = reset_identity(values)
  File ".../pandas/core/groupby.py", line 809, in reset_identity
    ax = v._get_axis(self.axis)
AttributeError: 'NoneType' object has no attribute '_get_axis'

----------------------------------------------------------------------
```

File: pandas/core/groupby.py [hunk 3]
```diff
@@ -3256,12 +3271,7 @@ def _wrap_applied_output(self, keys, values, not_indexed_same=False):
 
             # make Nones an empty object
             if com._count_not_none(*values) != len(values):
```
Comment (jreback) [inline pandas/core/groupby.py]: I think we can remove the ``_count_not_none(....)``

File: pandas/tests/test_groupby.py [hunk 4]
```diff
@@ -6279,6 +6279,22 @@ def test_func(x):
         expected = DataFrame()
         tm.assert_frame_equal(result, expected)
 
+    def test_groupby_apply_none_first(self):
+        # GH 12824. Tests if apply returns None first.
+        test_df = DataFrame({'groups': [0, 1, 1, 1],
+                             'vars': [8, 7, 4, 5]})
```
Comment (jreback) [inline pandas/tests/test_groupby.py]: add both test cases from the issue (1 already works, 1 you are fixing), so that they are in the same place.

**Comment by jreback** [comment]
can you squash

**Comment by jreback** [comment]
thanks @adneu
