### PR TITLE
DOC: Improve **kwargs docs for NumPy compatibility

### LINKED ISSUE #48423: DOC: Improve documentation of kwargs for NumPy compatibility
In certain locations, the API docs give very little information on kwargs that exist only for NumPy compatibility, e.g.

https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.sum.html

> Additional keyword arguments to be passed to the function.

https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.clip.html

> Additional keywords have no effect but might be accepted for compatibility with numpy.

This is a bit terse to me; I think it would be useful to have a section of the [FAQ](https://pandas.pydata.org/pandas-docs/dev/user_guide/gotchas.html) explaining this in a bit more detail.

### PR DESCRIPTION
**Pull request by pranavchoudhary-tech**
Closes #48423

### CODE REVIEW

File: doc/source/user_guide/gotchas.rst [hunk 1]
```diff
@@ -372,6 +372,15 @@ via ``object`` dtype:
...
    series.astype("object").prod()
 
+.. _gotchas.numpy_kwargs:
+
+NumPy compatibility kwargs
+--------------------------
+
+Many pandas methods accept additional keyword arguments (often passed as ``**kwargs``) to ensure compatibility with NumPy's API. This allows pandas objects to be passed to NumPy functions seamlessly. However, in many cases, these additional keywords have no effect on the behavior of the pandas method itself.
+
+For example, when using methods like :meth:`DataFrame.clip` or :meth:`DataFrame.sum`, the method signature includes ``**kwargs``. While you can pass additional arguments, they may be ignored by pandas if they are only meant for NumPy compatibility. This design choice prevents errors when NumPy attempts to pass its own arguments to the pandas object.
```
Comment (rhshadrach) [inline doc/source/user_guide/gotchas.rst]: This was true in the past, but we've been either validating or we've deprecated places where validation was not happening. If there are still places missing this, they should be addressed. I think the idea behind this section is good, but we should make this paragraph future proof in this regard.

Can you also explain why the keyword arguments are necessary for NumPy compatibility.

File: pandas/core/arrays/masked.py [hunk 2]
```diff
@@ -1932,7 +1932,7 @@ def all(
         axis : int, optional, default 0
         **kwargs : any, default None
             Additional keywords have no effect but might be accepted for
-            compatibility with NumPy.
+            compatibility with NumPy. See :ref:`gotchas.numpy_kwargs` for more.
```
Comment (rhshadrach) [inline pandas/core/arrays/masked.py:1971]: We now validate the arguments, so I don't think we need to say they have no effect. With your new section in the gotchas, I think we can be a bit more concise here.

> For compatibility with NumPy. See :ref:`gotchas.numpy_kwargs` for more.

File: pandas/core/groupby/generic.py [hunk 3]
```diff
@@ -1373,6 +1373,11 @@ def skew(
         **kwargs
             Additional keyword arguments to be passed to the function.
 
+            .. note::
+
+                Some kwargs may have no effect and are accepted only for
+                compatibility with NumPy. See :ref:`gotchas.numpy_kwargs` for more.
```
Comment (rhshadrach) [inline pandas/core/groupby/generic.py]: With the deprecation introduced in #64720, these kwargs will be removed. I don't think we need to make updates in such cases.

**Review by rhshadrach — CHANGES_REQUESTED** [review]
Thanks for the PR!

File: doc/source/user_guide/gotchas.rst [hunk 4]
```diff
@@ -372,6 +372,15 @@ via ``object`` dtype:
...
    series.astype("object").prod()
 
+.. _gotchas.numpy_kwargs:
+
+NumPy compatibility kwargs
+--------------------------
+
+Many pandas methods accept additional keyword arguments (often passed as ``**kwargs``) to ensure compatibility with NumPy's API. When a pandas object is passed to a NumPy function (for example, ``np.sum(df)``), NumPy will often pass its own arguments (such as ``out`` or ``keepdims``) to the pandas method. To prevent errors, pandas accepts these keywords.
+
+While pandas historically ignored many of these additional arguments, the library is moving towards strictly validating them or deprecating them where validation is missing. If you pass an argument that pandas does not implement, it may raise an error or emit a deprecation warning. You should only rely on the arguments explicitly documented in the pandas method signature.
```
Comment (rhshadrach) [inline doc/source/user_guide/gotchas.rst]: It currently reads that we may deprecating the argument if they don't have validation; we're only deprecating where they were never needed in the first place.

```suggestion
While pandas historically ignored many of these additional arguments, the library is moving towards strictly validating them or deprecating them where they are not necessary for NumPy compatibility. If you pass an argument that pandas does not implement, it may raise an error or emit a deprecation warning. You should only rely on the arguments explicitly documented in the pandas method signature.
```

File: pandas/core/resample.py [hunk 5]
```diff
@@ -1949,7 +1949,7 @@ def quantile(self, q: float | list[float] | AnyArrayLike = 0.5, **kwargs):
         q : float or array-like, default 0.5 (50% quantile)
             Value between 0 <= q <= 1, the quantile(s) to compute.
         **kwargs
-            Additional keyword arguments to be passed to the function.
+            For compatibility with NumPy. See :ref:`gotchas.numpy_kwargs` for more.
```
Comment (rhshadrach) [inline pandas/core/resample.py]: I believe this is incorrect - these are not for compatibility with NumPy and are actually passed on. Can you double check, and if so, revert this change.

File: pandas/core/frame.py [hunk 6]
```diff
@@ -16453,6 +16455,8 @@ def min(
         **kwargs
             Additional keyword arguments to be passed to the function.
```
Comment (rhshadrach) [inline pandas/core/frame.py]: I believe this is False and should be removed. This line appears in many places where it should be removed.

**Review by rhshadrach — CHANGES_REQUESTED** [review]
I think this is missing `Series.std` and other methods - var/sem/any/all/cummax etc. I can make an exhaustive list if it would be helpful.

@jorisvandenbossche - can I also get your eye on the new section in gotchas (the FAQ).

File: doc/source/user_guide/gotchas.rst [hunk 7]
```diff
@@ -372,6 +372,15 @@ via ``object`` dtype:
...
    series.astype("object").prod()
 
+.. _gotchas.numpy_kwargs:
+
+NumPy compatibility kwargs
+--------------------------
+
+Many pandas methods accept additional keyword arguments (often passed as ``**kwargs``) to ensure compatibility with NumPy's API. When a pandas object is passed to a NumPy function (for example, ``np.sum(df)``), NumPy will often pass its own arguments (such as ``out`` or ``keepdims``) to the pandas method. To prevent errors, pandas accepts these keywords.
+
+While pandas historically ignored many of these additional arguments, the library is moving towards strictly validating them or deprecating them where they are not necessary for NumPy compatibility. If you pass an argument that pandas does not implement, it may raise an error or emit a deprecation warning. You should only rely on the arguments explicitly documented in the pandas method signature.
```
Comment (jorisvandenbossche) [inline doc/source/user_guide/gotchas.rst]: Would it be useful to clarify what "validating" means exactly? As far as I understand, we validate that the keyword, if passed, has its default value?

**Comment by pranavchoudhary-tech** [comment]
Thanks for the review! I've applied the suggested change to the gotchas.rst text. I also went ahead and did an exhaustive pass to update the **kwargs docstrings for all the remaining statistical and aggregation methods you mentioned (including std, var, sem, skew, kurt, any, all, cummax, cummin, cumsum, cumprod) across both Series and DataFrame. Let me know if I missed any others!

File: doc/source/user_guide/gotchas.rst (hunk 7 above)
Comment (pranavchoudhary-tech) [reply doc/source/user_guide/gotchas.rst]: Great point! I agree that's much clearer. I've updated the text to clarify that validating means ensuring they are only passed with their default values.

File: doc/source/user_guide/gotchas.rst [hunk 8]
```diff
@@ -372,6 +372,15 @@ via ``object`` dtype:
    series.astype("float64").prod()
    series.astype("object").prod()
 
+.. _gotchas.numpy_kwargs:
+
+NumPy compatibility kwargs
+--------------------------
+
+Many pandas methods accept additional keyword arguments (often passed as ``**kwargs``) to ensure compatibility with NumPy's API. When a pandas object is passed to a NumPy function (for example, ``np.sum(df)``), NumPy will often pass its own arguments (such as ``out`` or ``keepdims``) to the pandas method. To prevent errors, pandas accepts these keywords.
```
Comment (jorisvandenbossche) [inline doc/source/user_guide/gotchas.rst]:
```suggestion
Many pandas methods accept additional keyword arguments (often passed as ``**kwargs``) to ensure compatibility with NumPy's API. When a pandas object is passed to a NumPy function (for example, ``np.sum(df)``), NumPy will often pass its own arguments (such as ``out`` or ``keepdims``) to the pandas method. To prevent errors, pandas accepts these keywords, if passed with their default value.
```

File: doc/source/user_guide/gotchas.rst [hunk 9]
```diff
@@ -372,6 +372,15 @@ via ``object`` dtype:
...
+
+While pandas historically ignored many of these additional arguments, the library is moving towards strictly validating them (i.e. ensuring they are only passed with their default values) or deprecating them where they are not necessary for NumPy compatibility. If you pass an argument that pandas does not implement, it may raise an error or emit a deprecation warning. You should only rely on the arguments explicitly documented in the pandas method signature.
```
Comment (jorisvandenbossche) [inline doc/source/user_guide/gotchas.rst]: Similarly as what Richard already commented before, but my feeling is that this is still a bit vague / not exactly true for the common cases.

For example, I checked the `np.sum(ser)` you used as an example above, and for me we correctly accept this for all of its optional arguments if I pass the default, and get an error if passing something else. 
Are there a lot of examples where this is not actually the case yet?

File: pandas/core/arrays/masked.py [hunk 10]
```diff
@@ -1837,8 +1837,7 @@ def any(
             if there are NA's present.
         axis : int, optional, default 0
         **kwargs : any, default None
-            Additional keywords have no effect but might be accepted for
-            compatibility with NumPy.
+            For compatibility with NumPy. See :ref:`gotchas.numpy_kwargs` for more.
```
Comment (jorisvandenbossche) [inline pandas/core/arrays/masked.py]: Do those keyword have an effect in this case? 

Otherwise I would keep the standard text of "additional keywords have no effect but might be accepted ...", as we have almost everywhere in the diff below

(and same just below)

File: pandas/core/resample.py (hunk 5 above)
Comment (jorisvandenbossche) [reply pandas/core/resample.py]: Can you actually keep the original text here? Because if they are passed to the numpy function, it is not just for "compatibility", but have an actual effect.

(in that case, I think we should actually document those explicitly, but let's leave that for another PR)

File: doc/source/user_guide/gotchas.rst (hunk 9 above)
Comment (pranavchoudhary-tech) [reply doc/source/user_guide/gotchas.rst]: Great point! I've updated the text to explicitly say that the library now strictly validates them rather than just moving towards it.

File: pandas/core/arrays/masked.py (hunk 10 above)
Comment (pranavchoudhary-tech) [reply pandas/core/arrays/masked.py]: You're right, they don't have an effect here. I've restored the standard text.

File: pandas/core/resample.py (hunk 5 above)
Comment (pranavchoudhary-tech) [reply pandas/core/resample.py]: Good catch! I've reverted the text back to the original here since they actually have an effect.

**Comment by pranavchoudhary-tech** [comment]
@rhshadrach @jorisvandenbossche I've pushed the updates to address all the feedback (including the exhaustive list of statistical methods and the wording tweaks).

Also, just a heads-up that the `Pyarrow Nightly` CI check is currently failing on the `Create virtual environment with Pixi` step, but this looks like an upstream infrastructure issue with the nightly wheel and is unrelated to these documentation changes.

The PR should be fully ready for another review and merge whenever you have a moment!

File: pandas/core/frame.py [hunk 11]
```diff
@@ -16453,6 +16456,8 @@ def min(
...
 
+            For compatibility with NumPy. See :ref:`gotchas.numpy_kwargs` for more.
```
Comment (rhshadrach) [inline pandas/core/frame.py]: I'm confused with what's going on here. The first line says additional arguments are passed to the function, and the added line says they are for NumPy compatibility. How can both be true?

**Comment by pranavchoudhary-tech** [comment]
I've updated the docstrings to remove the contradiction and use the standard NumPy compatibility wording. Tests are passing (except for the known Pyarrow Nightly failure). Let me know if anything else is needed!

**Review by rhshadrach — APPROVED** [review]
lgtm, you good here @jorisvandenbossche?

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!
