### ISSUE TITLE
BUG: Load ORC-format data failed when pandas version>1.2.0.dev0

### ISSUE THREAD

**Issue by amznero** [pandas-dev/pandas#40918]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.
https://github.com/pandas-dev/pandas/blob/master/pandas/io/orc.py#L15-L54

---

#### Code Sample, a copy-pastable example

```python
...
import pandas as pd
orc_data = pd.read_orc(orc_file_path)
```

#### Problem description

Pandas uses [PyArrow](https://arrow.apache.org/docs/python) package to load ORC/Parquet data. 

For the orc data format, it will use `pyarrow.orc.ORCFile` to read data ([orc.py](https://github.com/pandas-dev/pandas/blob/master/pandas/io/orc.py#L53)), but the PyArrow does not declare `orc` in [\_\_init\_\_.py](https://github.com/apache/arrow/blob/master/python/pyarrow/__init__.py) file, so pandas will raise an AttributeError: module 'pyarrow' has no attribute 'orc'

![image](https://user-images.githubusercontent.com/16681550/114521032-9da66800-9c74-11eb-8f03-11865f111be9.png)

This bug will occur if the Pandas version is greater than v1.2.0.dev0(after [commit-6d1541e](https://github.com/pandas-dev/pandas/commit/6d1541e1782a7b94797d5432922e64a97934cfa4)). Before that, `pandas/io/orc.py` will declare `import pyarrow.orc` before uses pyarrow to load orc data([v1.1.5/pandas/io.orc.py/](https://github.com/pandas-dev/pandas/blob/v1.1.5/pandas/io/orc.py#L51)).

---

Testing environment:

- Ubuntu 18.04
- python 3.7
- pandas v1.2.1
- pyarrow v3.0.0 (install via pip)(I haven't installed pyarrow via Conda for testing yet.)

**Comment by lithomas1** [comment]
pyarrow.orc doesn't seem to work in general for pyarrow > 0.15.0 I think. On pip, I get 
```
>>> import pyarrow.orc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\liwende\Anaconda3\lib\site-packages\pyarrow\orc.py", line 24, in <module>
    import pyarrow._orc as _orc
ModuleNotFoundError: No module named 'pyarrow._orc'
```
and with conda I get
```
>>> import pyarrow.orc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\liwende\Anaconda3\lib\site-packages\pyarrow\__init__.py", line 54, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: DLL load failed: The specified procedure could not be found.
```
(both with pyarrow 3.0.0)
Maybe related? https://issues.apache.org/jira/browse/ARROW-7811

**Comment by amznero** [comment]
Seems this problem(pyarrow.orc) is related to the operating system

I can run it successfully on Linux(Ubuntu), but I have the same problem as you mentioned on Windows10.

![image](https://user-images.githubusercontent.com/16681550/114669707-c2faab00-9d34-11eb-8f11-4bee4c422812.png)

---

Maybe related to https://stackoverflow.com/a/58967391
