### PR TITLE
TST: Groupby.filter dropna=False with empty group (#10780)

### LINKED ISSUE #10780: grouped.filter with dropna option
in Pandas 0.16.2:

```
grouped = a.groupby(idx)
grouped.filter(lambda x: x.mean()>0.0, dropna=False)
```

in case there was no group whose `x.mean()` was larger than zero, an `AttributeError: 'list' object has no attribute 'astype'` would be raised (rather than returning an all `NaN` dataframe/serie in previous versions).

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] closes #10780
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``

Didn't find a PR in 0.20 or 0.19.2 that closed this, but works on master 0.19.1

### CODE REVIEW

File: pandas/tests/groupby/test_filters.py [hunk 1]
```diff
@@ -596,6 +596,14 @@ def test_filter_non_bool_raises(self):
         with tm.assertRaisesRegexp(TypeError, 'filter function returned a.*'):
             df.groupby('a').filter(lambda g: g.c.mean())
 
+    def test_filter_dropna_false_with_empty_groups(self):
+        # GH 10780
+        data = pd.Series(np.random.rand(9), index=np.repeat([1, 2, 3], 3))
+        groupped = data.groupby(level=0)
+        result = groupped.filter(lambda x: x.mean() > 1, dropna=False)
```
Comment (jreback) [inline pandas/tests/groupby/test_filters.py]: can you add testing for ``dropna=True`` as well, for completeness

**Comment by mroeschke** [comment]
Added test for `dropna=True` and all green.

**Comment by jreback** [comment]
thanks!
