### PR TITLE
#14854: DatetimeIndex compiled together in test_datetime.py

### PR DESCRIPTION
**Pull request by TrigonaMinima**
### Partially completes #14854 

Grouped all the ```DatetimeIndex``` related tests under one file - ```pandas/tests/indexes/test_datetime.py```.

### Tests reorganized

There were some tests in other classes which could be shifted to the as well. From **```pandas/pandas/tseries/tests/test_timeseries.py```**

- [test_pass_datetimeindex_to_index](https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/tests/test_timeseries.py#L326) from class ```TestTimeSeries```
- [test_datetimeindex_accessors](https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/tests/test_timeseries.py#L3972) from class ```TestDatetime64```
- [test_datetimeindex_diff](https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/tests/test_timeseries.py#L4111) from class ```TestDatetime64```
- [test_nanosecond_field](https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/tests/test_timeseries.py#L4105) from class ```TestDatetime64```
- [test_datetimeindex_constructor](https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/tests/test_timeseries.py#L4146) from class ```TestDatetime64```

1. Should these also be included in the ```test_datetime.py``` in their respective classes or let them be?

2. In **```pandas/tests/indexes/test_datetimelike.py```** there were some tests which were using the ```DatetimeLike``` class defined there. I could import that class in the ```test_datetime.py``` and transfer the whole ```TestDatetimeIndex``` but should it be done?

### Mostly passes ``git diff upstream/master | flake8 --diff``

```
./pandas/tests/indexes/test_datetime.py:1121:5: F811 redefinition of unused 'test_intersection' from line 572
./pandas/tests/indexes/test_datetime.py:1751:5: F811 redefinition of unused 'test_union' from line 589
```
3. Should I merge the two ```test_intersection``` and ```test_union``` functions?

## Further TODOs from the following discussion and the #14854 under datetime

- [x] Split ```datetimes/test_datetime.py``` into smaller chunks

- [x] In ```datetimes/test_misc.py``` lines from 167-202 should go under timestamp related tests (?)

- [x] Transfer of function (```test_datetimeindex_accessors```) from class ```TestDatetime64``` in ```datetimes/test_misc.py``` to class ```TestDatetimeIndexOps``` of ```datetime/test_ops.py``` (?)

- [x] Function ```test_round``` from ```datetimes/test_datetime.py``` to ```pandas/tests/scalars/test_timestamp.py```. (and test_timedelta.py). So anything specifically Timestamp related will go there.

### CODE REVIEW

**Comment by jreback** [comment]
ok, so the resulting test file is just too big and unweildy.

let's split it out to a sub-dir, IOW

``pandas/tests/indexes/datetime``

then split into a number of files (you can start by splitting each class to a separate named file for instance)

**Comment by jreback** [comment]
nice start!

name things like

``test_ops.py`` (not ``test_datetimeops`` (except for the main 'test_datetime.py')

**Comment by TrigonaMinima** [comment]
Thanks. 

Though, ```test_datetime.py``` still looks big.

What about the questions I raised or is this PR ready?

**Comment by jreback** [comment]
> In pandas/tests/indexes/test_datetimelike.py there were some tests which were using the DatetimeLike class defined there. I could import that class in the test_datetime.py and transfer the whole TestDatetimeIndex but should it be done?

no ``DatetimeLike`` needs to be defined where it is as PeriodIndex tests use it (though it *could* be factorted to another file if need be)

**Comment by jreback** [comment]
> There were some tests in other classes which could be shifted to the as well. From pandas/pandas/tseries/tests/test_timeseries.py
test_pass_datetimeindex_to_index from class TestTimeSeries
test_datetimeindex_accessors from class TestDatetime64
test_datetimeindex_diff from class TestDatetime64
test_nanosecond_field from class TestDatetime64
test_datetimeindex_constructor from class TestDatetime64
Should these also be included in the test_datetime.py in their respective classes or let them be?

essentially yes these should be moved.

**Comment by jreback** [comment]
certainly would like to split up test_datetime.py Ideally split along class lines (though maybe not much there, it might already be a big class).

So can come back and do that later.

**Comment by jreback** [comment]
also need to add an entry in ``setup.py`` (right after ``pandas.tests.indexes``

**Comment by TrigonaMinima** [comment]
Now only remaining thing, it seems, is the merging of those 2 different function definitions by same name (```test_intersection``` and ```test_union```) in the ```pandas/tests/indexes/datetime/test_datetime.py```. I didn't do that because you said not to change individual tests.

**Comment by jreback** [comment]
@TrigonaMinima sure, let's get this passing. Then pls make a list of what changes you think could / should be made. We want to move and then in other commits, fix/change etc.

**Comment by TrigonaMinima** [comment]
@jreback I am sorry, I didn't understand you. Changes like? Merging those two functions and what else? Also, other commits under this PR only, right?

**Comment by TrigonaMinima** [comment]
Okay so here's the list I came up with

- [ ] Handle these flake errors

```
datetime/test_datetime.py:1117:5: F811 redefinition of unused 'test_intersection'
datetime/test_datetime.py:1747:5: F811 redefinition of unused 'test_union'
```
- [ ] In ```datetime/test_misc.py``` lines from 167-202 should go under timestamp related tests (?)

- [ ] Transfer of function (```test_datetimeindex_accessors```) from class ```TestDatetime64``` in ```datetime/test_misc.py``` to class ```TestDatetimeIndexOps``` of ```datetime/test_ops.py``` (?)

- [ ] Split ```datetime/test_datetime.py``` into smaller chunks

**Comment by jreback** [comment]
@TrigonaMinima if you can get this passing (iow fix the flake errors) would be great.

**Comment by TrigonaMinima** [comment]
@jreback the build in Python2.7 is giving errors in all the tests in ```pandas/tests/indexes``` due to import errors for ```datetime``` module. I am guessing it is trying to import the new ```datetime``` directory we have just made. It runs fine for Python3.5. 

Any suggestions? Change name of the directory is the easiest fix I can think of.

**Comment by jreback** [comment]
@TrigonaMinima change the directory name to datetimes I think will work

**Comment by jreback** [comment]
FYI you can do

``git diff master | flake8 --diff`` to see flake errors ahead of time

**Comment by TrigonaMinima** [comment]
Yeah. I read the full contributing guide yesterday.

Though, this module name problem wasn't showing up in the output of the command. Which is the right behavior given this isn't exactly a pep8 issue.

**Comment by jreback** [comment]
@TrigonaMinima yeah, for some reason travis catches slightly different things that local flake8, not really sure why (its only this particular pep, missing a whole module import)

File: pandas/tseries/tests/test_timeseries.py [hunk 1]
```diff
@@ -2718,1247 +2706,6 @@ def test_dataframe_dtypes(self):
...
-
-        ordered, dexer = idx.sort_values(return_indexer=True, ascending=False)
-        self.assertTrue(ordered[::-1].is_monotonic)
-        self.assert_numpy_array_equal(dexer,
-                                      np.array([0, 2, 1], dtype=np.intp))
-
-    def test_round(self):
-
-        # round
-        dt = Timestamp('20130101 09:10:11')
```
Comment (jreback) [inline pandas/tseries/tests/test_timeseries.py]: so this is something to add to the list.

I want to create a ``pandas/tests/scalars/test_timestamp.py`` (and test_timedelta.py). So anything specifically Timestamp related will go there.

this can be next iteration though.

File: pandas/tests/indexes/datetimes/test_datetime.py [hunk 2]
```diff
@@ -0,0 +1,1919 @@
...
+
+from pandas.util.testing import assert_series_equal, assert_almost_equal
+
+randn = np.random.randn
+
+
+class TestDatetimeIndex(tm.TestCase):
+    _multiprocess_can_split_ = True
+
+    def test_construction_with_alt(self):
```
Comment (jreback) [inline pandas/tests/indexes/datetimes/test_datetime.py]: so ok with splitting this up a bit now. e.g. test_construction (and when you do, copy the class (name), and leave the methods alone (even though they say ``test_construction_*`` for now that's ok))

File: pandas/tests/indexes/datetimes/test_datetime.py [hunk 3]
```diff
@@ -0,0 +1,1919 @@
...
+                 datetime(2013, 10, 9)]
+        data = DatetimeIndex(dates, freq=pd.tseries.frequencies.BDay()).values
+        result = DatetimeIndex(data, freq=pd.tseries.frequencies.BDay())
+        expected = DatetimeIndex(['2013-10-07',
+                                  '2013-10-08',
+                                  '2013-10-09'],
+                                 freq='B')
+        tm.assert_index_equal(result, expected)
+
+    def test_astype(self):
```
Comment (jreback) [inline pandas/tests/indexes/datetimes/test_datetime.py]: test_astype.py

File: pandas/tests/indexes/datetimes/test_datetime.py [hunk 4]
```diff
@@ -0,0 +1,1919 @@
...
+        # GH 13149, GH 13209
+        idx = DatetimeIndex(['2016-05-16', 'NaT', NaT, np.NaN])
+
+        self.assertRaises(ValueError, idx.astype, float)
+        self.assertRaises(ValueError, idx.astype, 'timedelta64')
+        self.assertRaises(ValueError, idx.astype, 'timedelta64[ns]')
+        self.assertRaises(ValueError, idx.astype, 'datetime64')
+        self.assertRaises(ValueError, idx.astype, 'datetime64[D]')
+
+    def test_where_other(self):
```
Comment (jreback) [inline pandas/tests/indexes/datetimes/test_datetime.py]: test_indexing.py

File: pandas/tests/indexes/datetimes/test_datetime.py [hunk 5]
```diff
@@ -0,0 +1,1919 @@
...
+            self.assertEqual(result.freq, '3D')
+
+        for result in [idx - delta, np.subtract(idx, delta)]:
+            tm.assertIsInstance(result, DatetimeIndex)
+            exp = DatetimeIndex(['2010-12-31', '2011-01-01', '2011-01-02'],
+                                freq='D', name='x')
+            tm.assert_index_equal(result, exp)
+            self.assertEqual(result.freq, 'D')
+
+    def test_fillna_datetime64(self):
```
Comment (jreback) [inline pandas/tests/indexes/datetimes/test_datetime.py]: test_missing.py

File: pandas/tests/indexes/datetimes/test_datetime.py [hunk 6]
```diff
@@ -0,0 +1,1919 @@
...
+                idx.fillna(pd.Timestamp('2011-01-01 10:00')), exp)
+
+            # object
+            exp = pd.Index([pd.Timestamp('2011-01-01 09:00', tz=tz),
+                            'x',
+                            pd.Timestamp('2011-01-01 11:00', tz=tz)],
+                           dtype=object)
+            self.assert_index_equal(idx.fillna('x'), exp)
+
+    def test_difference_freq(self):
```
Comment (jreback) [inline pandas/tests/indexes/datetimes/test_datetime.py]: test_setops. (include union, intersection, difference routines)

File: pandas/tests/indexes/datetimes/test_datetime.py [hunk 7]
```diff
@@ -0,0 +1,1919 @@
...
+        tm.assert_index_equal(idx.to_period(), expected)
+
+    def test_000constructor_resolution(self):
+        # 2252
+        t1 = Timestamp((1352934390 * 1000000000) + 1000000 + 1000 + 1)
+        idx = DatetimeIndex([t1])
+
+        self.assertEqual(idx.nanosecond[0], t1.nanosecond)
+
+    def test_constructor_coverage(self):
```
Comment (jreback) [inline pandas/tests/indexes/datetimes/test_datetime.py]: another one for test_construction

File: pandas/tests/indexes/datetimes/test_datetime.py [hunk 8]
```diff
@@ -0,0 +1,1919 @@
...
+        result = rng.groupby(rng.day)
+        tm.assertIsInstance(list(result.values())[0][0], Timestamp)
+
+        idx = DatetimeIndex(['2000-01-03', '2000-01-01', '2000-01-02'])
+        self.assertFalse(idx.equals(list(idx)))
+
+        non_datetime = Index(list('abc'))
+        self.assertFalse(idx.equals(list(non_datetime)))
+
+    def test_union_coverage(self):
```
Comment (jreback) [inline pandas/tests/indexes/datetimes/test_datetime.py]: to test_setops

File: pandas/tests/indexes/datetimes/test_datetime.py [hunk 9]
```diff
@@ -0,0 +1,1919 @@
...
+                       index=date_range('1/1/2000', periods=10))
+
+        result = df.loc['1/3/2000']
+        self.assertEqual(result.name, df.index[2])
+
+        result = df.T['1/3/2000']
+        self.assertEqual(result.name, df.index[2])
+
+    # GH 10699
+    def test_datetime64_with_DateOffset(self):
```
Comment (jreback) [inline pandas/tests/indexes/datetimes/test_datetime.py]: can go to test_ops

File: pandas/tests/indexes/datetimes/test_datetime.py [hunk 10]
```diff
@@ -0,0 +1,1919 @@
...
+        self.assertTrue(result.freq is None)
+
+        # GH 7299
+        tm._skip_if_no_pytz()
+        import pytz
+
+        idx = date_range('1/1/2000', periods=3, freq='D', tz='Asia/Tokyo',
+                         name='idx')
+        with tm.assertRaises(ValueError):
+            result =
```
Comment (jreback) [inline pandas/tests/indexes/datetimes/test_datetime.py]: put insert and delete into test_setops as well

Comment (jreback) [inline pandas/tests/indexes/datetimes/test_datetime.py]: take -> test_indexing

**Comment by jreback** [comment]
thanks @TrigonaMinima !

ok I am going to push a scalar directory now that is empty, but please continue on moving things!
