### ISSUE TITLE
ENH: reading Parquet with PyArrrow : read_parquet equivalent of date_as_object=False

### ISSUE THREAD

**Issue by simonaubertbd** [pandas-dev/pandas#62262]
### Feature Type

- [ ] Adding new functionality to pandas

- [x] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Hello,

This follows https://github.com/apache/arrow/issues/47464#issuecomment-3257645492

To quote the excellente answer I got 
`Parquet has a date type, and Arrow as well. And so when reading the Parquet file into an Arrow table using pyarrow, you would see that the type is preserved. You can try:

import pyarrow.parquet as pq
table = pq.read_table("C:/Users/qnsv2207/Desktop/test_amphi_compare.parquet")
table

This should show that the "OrderDate" column has a date32 type.

But then pandas does not have a built-in "date" type. Therefore, in the arrow->pandas conversion, pyarrow by default converts its date types into an object column with python datetime.date objects.

See the documentation about this at https://arrow.apache.org/docs/python/pandas.html#date-types, which also mentions the date_as_object=False option you can specify in to_pandas() to avoid this conversion to object dtype.`

But there is no way to pass in read_parquet equivalent of date_as_object=False as far as I understand the documentation

### Feature Description

A new parameter for read_parquet equivalent of pyarrow date_as_object
I would even set the default to treat pyarrow date as date in pandas

### Alternative Solutions

Not using pandas to read parquet but directly pyarrows. Doesn't sound practical..

**Comment by sj-infocusp** [comment]
take

**Comment by simonaubertbd** [comment]
@sj-infocusp thanks !

**Comment by sj-infocusp** [comment]
I'm using the below version in venv:
```
Package         Version
--------------- -----------
cramjam         2.11.0
fastparquet     2024.11.0
fsspec          2025.9.0
numpy           2.3.3
packaging       25.0
pandas          2.3.2
pip             24.0
pyarrow         21.0.0
python-dateutil 2.9.0.post0
pytz            2025.2
six             1.17.0
tzdata          2025.2
```

Below is a sample code to save pandas df in parquet file and then reading the same parquet file via pandas and pyarrow.

```
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

# Sample data with datetime dates
data = {
    "dates": pd.to_datetime(["2023-01-01", "2023-06-15", "2024-12-31", "1965-01-23"]),
    "values": [10, 20, 30, 35],
}

df = pd.DataFrame(data)

print(
    "\n\n-----------------------------------------------------------------------------------------\n\n"
)
print("Input dataframe and datatype:")

# Display the dataframe
print(df)

# Display datatypes
print("\nData types:")
print(df.dtypes)

# Convert pandas datetime to Arrow date32 type explicitly
table = pa.Table.from_pandas(
    # df, schema=pa.schema([("dates", pa.timestamp(unit="s")), ("values", pa.int64())])
    df,
    schema=pa.schema([("dates", pa.date32()), ("values", pa.int64())]),
)

print(
    "\n\n-----------------------------------------------------------------------------------------\n\n"
)

print("Pyarrow table:")
print(table)

# Write to Parquet file
pq.write_table(table, "output.parquet")

print("Parquet file written with date32 datatype.")


# -----------------------------------------------------------------------
# Read the parquet file
# -----------------------------------------------------------------------
print(
    "\n\n-----------------------------------------------------------------------------------------\n\n"
)
print("Reading parquet file with pandas:\n")
# df = pd.read_parquet("output.parquet", to_pandas_kwargs={"date_as_object": False})    # TypeError: read_table() got an unexpected keyword argument 'to_pandas_kwargs'
df = pd.read_parquet("output.parquet", engine="auto")

# Display the dataframe
print(df)

# Display datatypes
print("\nData types:")
print(df.dtypes)


# -----------------------------------------------------------------------
# Read the parquet file using dtype_backend="pyarrow"
# -----------------------------------------------------------------------
print(
    "\n\n-----------------------------------------------------------------------------------------\n\n"
)
print("Reading parquet file with pandas using dtype_backend='pyarrow':")
df = pd.read_parquet("output.parquet", dtype_backend="pyarrow")

# Display the dataframe
print(df)

# Display datatypes
print("\nData types:")
print(df.dtypes)

print(
    "\n\n-----------------------------------------------------------------------------------------\n\n"
)
```


Output:

```

-----------------------------------------------------------------------------------------


Input dataframe and datatype:
       dates  values
0 2023-01-01      10
1 2023-06-15      20
2 2024-12-31      30
3 1965-01-23      35

Data types:
dates     datetime64[ns]
values             int64
dtype: object


-----------------------------------------------------------------------------------------


Pyarrow table:
pyarrow.Table
dates: date32[day]
values: int64
----
dates: [[2023-01-01,2023-06-15,2024-12-31,1965-01-23]]
values: [[10,20,30,35]]
Parquet file written with date32 datatype.


-----------------------------------------------------------------------------------------


Reading parquet file with pandas:

        dates  values
0  2023-01-01      10
1  2023-06-15      20
2  2024-12-31      30
3  1965-01-23      35

Data types:
dates     object
values     int64
dtype: object


-----------------------------------------------------------------------------------------


Reading parquet file with pandas using dtype_backend='pyarrow':
        dates  values
0  2023-01-01      10
1  2023-06-15      20
2  2024-12-31      30
3  1965-01-23      35

Data types:
dates     date32[day][pyarrow]
values          int64[pyarrow]
dtype: object


-----------------------------------------------------------------------------------------

```


However this seem to be fixed in the new version: [https://github.com/pandas-dev/pandas/blob/d4bac86ba3bae0c88d3e8f4e74a5c7197912d288/doc/source/whatsnew/v3.0.0.rst#L203:~:text=%3Afunc%3A%60read_parquet%60%20accepts%20to_pandas_kwargs%20which%20are%20forwarded%20to%20%3Ameth%3A%60pyarrow.Table.to_pandas%60%20which%20enables%20passing%20additional%20keywords%20to%20customize%20the%20conversion%20to%20pandas%2C%20such%20as%20maps_as_pydicts%20to%20read%20the%20Parquet%20map%20data%20type%20as%20python%20dictionaries%20(%3Aissue%3A%6056842%60)](url)


We can now use the below code and pass keyword args for to_pandas():

`df = pd.read_parquet("output.parquet", to_pandas_kwargs={"date_as_object": False})`

**Comment by sj-infocusp** [comment]
Hello @simonaubertbd and @jbrockmendel 
Any update/comment on this?

**Comment by jbrockmendel** [comment]
Does `df = pd.read_parquet("output.parquet", to_pandas_kwargs={"date_as_object": False})` not work?  Your previous comment said it works.

**Comment by simonaubertbd** [comment]
@sj-infocusp  @jbrockmendel doesn't seem to work with pandas 2.3.3. :(
`TypeError: read_table() got an unexpected keyword argument 'to_pandas_kwargs'`

**Comment by sj-infocusp** [comment]
@simonaubertbd @jbrockmendel 
Yes, `to_pandas_kwargs` doesn't work with pandas 2.3.3.

Please refer to [https://github.com/pandas-dev/pandas/blob/d4bac86ba3bae0c88d3e8f4e74a5c7197912d288/doc/source/whatsnew/v3.0.0.rst#L203](https://github.com/pandas-dev/pandas/blob/d4bac86ba3bae0c88d3e8f4e74a5c7197912d288/doc/source/whatsnew/v3.0.0.rst#L203 )

The `to_pandas_kwargs` will be available from version 3.0.0.

**Comment by simonaubertbd** [comment]
Back on this issue : the {"date_as_object": False} should be the default behaviour. A human sees a date in parquet, he expects a date in pandas by default.

**Comment by rhshadrach** [comment]
Mentioned above, this was added in #56842 as `pd.read_parquet(path, to_pandas_kwargs={"date_as_object": False})`. 2.x will not see this feature. Closing.
