### PR TITLE
REGR: Restore _constructor_from_mgr to pass manager object to constructor

### LINKED ISSUE #55120: BUG: Infinite recursion on inheritance and overloading `__getattr__` in `v2.1.0`
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
from contextlib import suppress
import pandas as pd

class TfsDataFrame(pd.DataFrame):
    """
    Extend DataFrame to add headers, which should be accessed in case 
    the name is not found in the DataFrame itself, but also 
    can be accessed manually by the `headers` attribute.
    """

    _metadata = ["headers"]

    def __init__(self, *args, **kwargs):
        self.headers = {}
        with suppress(IndexError, AttributeError):
            self.headers = args[0].headers
        self.headers = kwargs.pop("headers", self.headers)
        super().__init__(*args, **kwargs)

    def __getattr__(self, name: str) -> object:
        try:
            return super().__getattr__(name)
        except AttributeError:
            pass
        
        try:
            return self.headers[name]
        except KeyError:
            raise AttributeError(f"{name} is neither in the DataFrame nor in headers.")

    @property
    def _constructor(self):
        return TfsDataFrame


if __name__ == "__main__":
    df = TfsDataFrame(columns=["A", "B", "C"])
    print(df[["A", "B"]])
```

### Issue Description

This is a reduced example of a `DataFrame` extension, that we have been using for years now and it worked fine until version `2.0.3` (including), but broke with `2.1.0`.

From `2.1.0` the code above runs into an infinite recursion loop, as `df[["A", "B"]]` creates a new `TfsDataFrame` (due to the `_constructor`).
In its `__init__` the `args[0]` is then already a `TfsDataFrame` object but`args[0].headers` for some reason calls `__getattr__()` as does `self.headers[name]` in the `__getattr__()` function, causing the infinite recursion.

This was not the case in the past, as `.headers` should be finding the attribute `headers` "directly", without even going to `__getattr__()`.

Interestingly, 
```python
df = TfsDataFrame(columns=["A", "B", "C"])
print(df.headers)

df = TfsDataFrame(columns=["A", "B", "C"], headers={"a":1})
print(df.headers["a"])
```
are indeed working as intended.

This is the most direct recursion loop I could find, but actually with `2.1.0` we have experienced extended recursion loops, which  can create infinite runtime.

### Expected Behavior

Should not end up in an infinite recursion.
As is the case e.g. in `pandas` version `2.0.3`.

Thank you very much for your help and your effort maintaining `pandas`. 
Its amazing set of features have made our work with measurement data much more comfortable and streamlined,
not to mention the highly increased readability of our code compared to anno BP (before pandas).

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : ba1cccd19da778f0c3a7d6a885685da16a072870
python              : 3.9.7.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 5.14.0-162.18.1.el9_1.x86_64
Version             : #1 SMP PREEMPT_DYNAMIC Tue Feb 28 03:54:43 EST 2023
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : C.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.0
numpy               : 1.25.2
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 59.5.0
pip                 : 21.3.1
Cython              : 0.29.35
pytest              : 7.3.1
hypothesis          : 6.75.8
sphinx              : 6.2.1
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.14.0
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.7.1
numba               : None
numexpr             : 2.8.4
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.2
sqlalchemy          : None
tables              : 3.8.0
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : 2.3.1
pyqt5               : None

</details>

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
See https://github.com/pandas-dev/pandas/pull/53871#discussion_r1251901671 for context. This reverts the refactoring changes of the `_constructor_.._from_mgr` methods of https://github.com/pandas-dev/pandas/pull/53871 to the state of the original PR https://github.com/pandas-dev/pandas/pull/52132 that added those new methods. 

This _does_ keep the other changes of that PR (i.e. using `_constructor_from_mgr` in more places). @jbrockmendel mentioned he got some AttributeErrors related to `_name` not yet being defined, but at the moment the tests seem to pass anyway.

Closes https://github.com/pandas-dev/pandas/issues/55120

### CODE REVIEW

**Comment by jbrockmendel** [comment]
The motivation is that geopandas does something involving inference on object dtypes differently if it gets a Manager object?  Can you elaborate on that?

**Comment by lithomas1** [comment]
Bumping off the milestone, assuming the release happens tomorrow.

**Comment by lithomas1** [comment]
CI is failing, bumping off the release.

**Comment by jorisvandenbossche** [comment]
@lithomas1 if you bump something (at least for regressions), can you please bump it to the _next_ bug-fix milestone (although I assume in general for PRs that's not a problem, as long as you bump issues to the next milestone instead of removing the milestone. So I should have opened an issue for this one ;))

**Comment by jorisvandenbossche** [comment]
> The motivation is that geopandas does something involving inference on object dtypes differently if it gets a Manager object? Can you elaborate on that?

@jbrockmendel yes, whenever we get a manager, we don't do _any_ inference, while if we get object dtype array, we do some inference (and then potentially fallback to DataFrame instead of GeoDataFrame in case there are no geometries). See also my geopandas PR related to this: https://github.com/geopandas/geopandas/pull/3046

But that's geopandas specific (and something we can handle by overriding the constructor from mgr), while this PR actually addresses a more general issue: with your change in https://github.com/pandas-dev/pandas/pull/53871, creating a Series or DataFrame object with `self._from_mgr` and passing that to `_constructor`, the _consequence_ of this is that we are now passing a non-fully initialized object to the subclass constructor. And there is no guarantee that the subclass constructor works with such partial objects. 

Essentially, this is the same as https://github.com/pandas-dev/pandas/pull/55607, where `Series._from_mgr` currently returns an non-fully initialized Series object (there is an attribute missing, so some methods don't work). Similarly for subclasses, when this is created with `_from_mgr`, it didn't go through the subclass' `__init__` function, and does the subclass object might not be fully correctly be set up.

I think, when passing (subclassed) DataFrame/Series objects to the public constructor (`__init__`), one should always be able to assume that this are valid, fully-initialized objects. 

I added a generic test that demonstrates this (`test_constructor_with_metadata` in `frame/test_subclass.py`). This test works on 2.0, but fails on 2.1.1.

**Comment by jorisvandenbossche** [comment]
I am adding a bunch of filterwarnings here, while of course we should fix those cases properly. But I decided to go with the filtering here, because firstly those warnings don't yet exist on 2.1.x and so properly fixing them isn't need to backport. And secondly, we then also have a bit more time to figure out the best way we want to have subclasses deal with this (eg Brock's comment at https://github.com/geopandas/geopandas/pull/3046/files#r1371974580 might mean we want to tweak a bit the way that subclasses interact with this). I am also not sure whether we actually want to let all subclasses deal with this, instead of rather doing it as a breaking change in eg 3.0 (or let subclasses handle a mgr in their main constructor)

**Comment by jorisvandenbossche** [comment]
To illustrate the issue with our own Series:

```
In [4]: s = pd.Series([1, 2, 3], name="test")

In [5]: pd.Series(pd.Series._from_mgr(s._mgr, s._mgr.axes))
...
AttributeError: 'Series' object has no attribute '_name'
```

So our Series `__init__` doesn't work with partially-initialized Series object. We solve that on our side by adding `s._name` inside `Series._constructor_from_mgr`, but subclasses can also have this kind of attributes that have to be added to be able to work properly. And so those subclasses would need to override `_from_mgr` or `_constructor_from_mgr` to do that (and that's something we need to document, and decide how to move towards that, instead of already breaking that in 2.1.x)

**Comment by jbrockmendel** [comment]
no objection to getting this in for 2.1.x, can figure out a longer-term plan later

**Comment by jorisvandenbossche** [comment]
Manual backport -> https://github.com/pandas-dev/pandas/pull/55704
