### ISSUE TITLE
BUG: Series.count() raises exception after upgrading from v0.24.1 to v0.25.3  if use_inf_as_na is enabled for a DateTime series.

### ISSUE THREAD

**Issue by thy09** [pandas-dev/pandas#29478]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
from datetime import datetime

if __name__ == '__main__':
    s = pd.Series([datetime.now()])
    with pd.option_context('use_inf_as_na', True):
        s.count()
```
#### Problem description

Previously with pandas v0.24.1, the above code works well,
however, after I upgrade the version to v0.25.3,
the above code raises an exception:
`AttributeError: 'DatetimeArray' object has no attribute '_constructor'`

It seems that something goes wrong when passing a `DatetimeArray` to `_isna_old`.
I think it is a bug introduced in some recent update.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.3
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 18.1
setuptools       : 40.6.2
Cython           : None
pytest           : 4.3.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.12.1
pytables         : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by jorisvandenbossche** [comment]
@thy09 late reply, but thanks for the report! I can confirm this is a regression compared to 0.24

I think the fix should be to add `ExtensionArray` to this isinstance check here:

https://github.com/pandas-dev/pandas/blob/35029d20d53a1af57823759039f57d8ff09736c3/pandas/core/dtypes/missing.py#L178

You're certainly welcome to look into it and do a PR!

**Comment by thy09** [comment]
In `_isna_new`, I see 3 more types `ABCExtensionArray, ABCDatetimeArray, ABCTimedeltaArray,`,
should we follow the same logic and add these three types to `isna_old`?

**Comment by jorisvandenbossche** [comment]
Normally, if something is a DatetimeArray or TimedeltaArray, it is also an ExtensionArray (it are subclasses), so I would think that only adding `ABCExtensionArray` would be enough. But you might need to test that.
