### PR TITLE
ENH: Add HalfYear offsets

### LINKED ISSUE #22362: Add "semester" as a time/date component to DatetimeIndex
#### Groupby is missing "semester"

```
from datetime import *
import pandas as pd
import numpy as np

df = pd.DataFrame()

days = pd.date_range(start="2017-05-17", 
                     end="2017-11-29",
                    freq="1D")
df = pd.DataFrame({'DTIME': days, 'DATA': np.random.randint(50, high=80, size=len(days))})
df.set_index('DTIME', inplace=True)

grouped = df.groupby(pd.Grouper(freq='2QS'))  # group by 2 Quarters,  start
print("Groups date start:")
for dtime, group in grouped:
    print dtime
    # print(group)
```
returns groups based on the first date time index of the dataset, not on the year semesters that begin on _January, 1st_ and _July, 1st_:

```
Groups date start:
2017-04-01 00:00:00    <=== this is because the first datetime index is in  May, 2017
2017-10-01 00:00:00
```
while I would expect:

```
Groups date start:
2017-01-01 00:00:00   
2017-07-01 00:00:00
```

This issue is difficult to spot, as the behaviour changes according to the dataset, while it should be consistent. I didn't spot it with my first dataset (starting on January).

The same problem will show when grouping by 6MS (six months, start)

Semester frequency is missing from Pandas'[offset-aliases](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases)

### LINKED ISSUE #60928: ENH: Control resampling at halfyear with origin
### Pandas version checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
s1 = pd.Series(1, pd.date_range('2025', freq='D', periods=700)).resample('2QS-JAN').sum()
s2 = pd.Series(1, pd.date_range('2025-04', freq='D', periods=700)).resample('2QS-JAN').sum()

# s1 expectedly has timestamps in january and july
# s1
# 2025-01-01    181
# 2025-07-01    184
# 2026-01-01    181
# 2026-07-01    154
# Freq: 2QS-JAN, dtype: int64    # NB frequency

# but s2 unexpectedly has timestamps in april and october
# s2
# 2025-04-01    183
# 2025-10-01    182
# 2026-04-01    183
# 2026-10-01    152
# Freq: 2QS-JAN, dtype: int64    # NB frequency

s1.index.freq == s2.index.freq   # True
```

### Issue Description

It seems there is no way to force where the period boundaries are when resampling at the 2-Quarter frequency. Resampling at `2QS-APR` gives the same results for `s1` and `s2` as those shown above.

### Expected Behavior

I'd expect the index of `s2` to also have timestamps on the first of January and July.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.10.12
python-bits           : 64
OS                    : Linux
OS-release            : 6.9.3-76060903-generic
Version               : #202405300957~1738770968~22.04~d5f7c84 SMP PREEMPT_DYNAMIC Wed F
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : C.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.3
numpy                 : 1.26.4
pytz                  : 2024.2
dateutil              : 2.9.0.post0
pip                   : 24.3.1
Cython                : None
sphinx                : 7.3.7
IPython               : 8.29.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : 3.1.4
lxml.etree            : None
matplotlib            : 3.9.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : 8.3.3
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : 0.9.0
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2024.2
qtpy                  : None
pyqt5                 : None
</details>

### PR DESCRIPTION
**Pull request by snitish**
- [ ] closes #60928
- [ ] closes #22362
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by snitish** [comment]
@rhshadrach I was able to add the half-year offset classes without too much added complexity. However, I haven't enabled them to be used as periods/frequencies - that will take more code changes and tests. Do you recommend concluding this here or go all the way to supporting half-year periods/frequencies? cc: @MarcoGorelli

**Review by rwijtvliet — COMMENTED** [review]
Looks great sofar to me

**Comment by rhshadrach** [comment]
@snitish - I think holding off on periods makes sense. This is already a sizable PR.

**Review by rhshadrach — APPROVED** [review]
lgtm

File: pandas/_libs/tslibs/offsets.pyx [hunk 1]
```diff
@@ -3011,6 +3011,228 @@ cdef class QuarterBegin(QuarterOffset):
...
+# ----------------------------------------------------------------------
+# HalfYear-Based Offset Classes
+
+cdef class HalfYearOffset(SingleConstructorOffset):
+    _attributes = tuple(["n", "normalize", "startingMonth"])
+    # TODO: Consider combining HalfYearOffset, QuarterOffset and YearOffset
+
+    # FIXME(cython#4446): python annotation here gives compile-time errors
+    # _default_starting_month: int
+    # _from_name_starting_month: int
```
[the remark this answers is not in the document]
Comment (snitish) [reply pandas/_libs/tslibs/offsets.pyx:3023]: Unfortunately, this is not resolved yet. Still throws compile time errors when I uncomment those lines -
```
  pandas/_libs/tslibs/offsets.cpython-310-darwin.so.p/pandas/_libs/tslibs/offsets.pyx.c:98384:21: error: use of undeclared identifier '__pyx_base'
   98384 |   __Pyx_XDECREF_SET(__pyx_base._default_starting_month, ((PyObject*)__pyx_t_2));
         |                     ^
  pandas/_libs/tslibs/offsets.cpython-310-darwin.so.p/pandas/_libs/tslibs/offsets.pyx.c:98384:21: error: use of undeclared identifier '__pyx_base'; did you mean '__pyx_k_base'?
   98384 |   __Pyx_XDECREF_SET(__pyx_base._default_starting_month, ((PyObject*)__pyx_t_2));
         |                     ^~~~~~~~~~
         |                     __pyx_k_base
```

[the remark this answers is not in the document]
Comment (rhshadrach) [reply pandas/_libs/tslibs/offsets.pyx:3023]: I think the resolution would be type-hinting as:

    _default_starting_month: typing.ClassVar[int]

That's what I'm wondering will work with Cython 3.0.

[the remark this answers is not in the document]
Comment (snitish) [reply pandas/_libs/tslibs/offsets.pyx]: Ah yes, that seems to have fixed it. Thanks!

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks again @snitish
