### PR TITLE
Backport PR #39795 on branch 1.2.x (fix benchmark failure with numpy 1.20+)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #39795: fix benchmark failure with numpy 1.20+

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
ImportError: cannot import name 'np_version_under1p20' from 'pandas.compat.numpy'

will fix up shortly

**Comment by simonjayhawkins** [comment]
The changes that caused the failure were added in #38379 which is on master, milestoned 1.3 and not on 1.2.x

this backport is not needed, so closing
