### ISSUE TITLE
REGR: CategoricalIndex and IntervalIndex are missing _index_data attribute

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#31248]
It looks like the `_index_data` attribute wasn't added to `CategoricalIndex` or `IntervalIndex`.  This leads to some regressions with `GroupBy.apply`.

Not sure what the fix should be, as there isn't a singular array that directly backs the underlying values for `CategoricalIndex` or `IntervalIndex`, so the approach used to add `_index_data` for other types doesn't look like it will work here.

Example of broken behavior on `master`:
```python
In [1]: import pandas as pd; pd.__version__
Out[1]: '1.0.0rc0+146.g6f395ad42'

In [2]: index = pd.CategoricalIndex(list("abc"))  
   ...: df = pd.DataFrame({"group": [0, 0, 1], "value": [1, 2, 3]}, index=index)

In [3]: df.groupby("group").apply(lambda x: x)
---------------------------------------------------------------------------
AttributeError: 'CategoricalIndex' object has no attribute '_index_data'

```

Same behavior worked on 0.25.3:
```python
In [1]: import pandas as pd; pd.__version__
Out[1]: '0.25.3'

In [2]: index = pd.CategoricalIndex(list("abc"))  
   ...: df = pd.DataFrame({"group": [0, 0, 1], "value": [1, 2, 3]}, index=index)

In [3]: df.groupby("group").apply(lambda x: x)
Out[3]: 
   group  value
a      0      1
b      0      2
c      1      3
```
Swapping `CategoricalIndex` with `IntervalIndex` results in the same behavior above.

**Comment by TomAugspurger** [comment]
@jbrockmendel do you have thoughts on how to fix this?

**Comment by jschendel** [comment]
@TomAugspurger : This can be fixed by excluding these index types from the `libreduction` path by checking against the `_has_complex_internals` property as I've defined it in #31238.  Just a matter of merging that PR first so `_has_complex_internals` is available (or doing this fix as part of that PR).

**Comment by TomAugspurger** [comment]
Thanks. I think that PR can contain the check as well.

**Comment by jbrockmendel** [comment]
I think @jschendel is on the right track with just avoiding _index_data altogether.  For CategoricalIndex we _could_ kludge it together, but I don't think its possible for IntervalIndex.
