### PR TITLE
REGR: Prevent indexes that aren't directly backed by numpy from entering libreduction code paths

### LINKED ISSUE #31223: GroupBy aggregation fails if DataFrame has CategoricalIndex
#### Code Sample, a copy-pastable example if possible

```python
ids = pd.Categorical([0, 1, 2])
df = pd.DataFrame({
    'id': ids,
    'groups': [1, 1, 2],
    'value': [0, 1, 0]
}).set_index('id')

df.groupby('groups').agg({'value': pd.Series.nunique})

```
#### Problem description
The above works in v. `0.25.3` but not in `1.0.0rc0`. It fails with: `TypeError: Cannot convert Categorical to numpy.ndarray` 

Full stack trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.virtualenvs/3.6-test-pd-1.0.0/lib/python3.6/site-packages/pandas/core/groupby/generic.py", line 940, in aggregate
    result, how = self._aggregate(func, *args, **kwargs)
  File "~/.virtualenvs/3.6-test-pd-1.0.0/lib/python3.6/site-packages/pandas/core/base.py", line 430, in _aggregate
    result = _agg(arg, _agg_1dim)
  File "~/.virtualenvs/3.6-test-pd-1.0.0/lib/python3.6/site-packages/pandas/core/base.py", line 397, in _agg
    result[fname] = func(fname, agg_how)
  File "~/.virtualenvs/3.6-test-pd-1.0.0/lib/python3.6/site-packages/pandas/core/base.py", line 381, in _agg_1dim
    return colg.aggregate(how)
  File "~/.virtualenvs/3.6-test-pd-1.0.0/lib/python3.6/site-packages/pandas/core/groupby/generic.py", line 265, in aggregate
    return self._python_agg_general(func, *args, **kwargs)
  File "~/.virtualenvs/3.6-test-pd-1.0.0/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 935, in _python_agg_general
    result, counts = self.grouper.agg_series(obj, f)
  File "~/.virtualenvs/3.6-test-pd-1.0.0/lib/python3.6/site-packages/pandas/core/groupby/ops.py", line 624, in agg_series
    return self._aggregate_series_fast(obj, func)
  File "~/.virtualenvs/3.6-test-pd-1.0.0/lib/python3.6/site-packages/pandas/core/groupby/ops.py", line 648, in _aggregate_series_fast
    grouper = libreduction.SeriesGrouper(obj, func, group_index, ngroups, dummy)
  File "pandas/_libs/reduction.pyx", line 329, in pandas._libs.reduction.SeriesGrouper.__init__
TypeError: Cannot convert Categorical to numpy.ndarray
```
#### Expected Output
The correct result applying the aggregation function to the DataFrameGroupBy

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.0rc0
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.1
setuptools       : 45.1.0
Cython           : None
pytest           : 5.2.0
hypothesis       : None
sphinx           : 2.0.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.2.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.0.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.2.0
s3fs             : 0.4.0
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : 0.47.0
</details>

### LINKED ISSUE #31248: REGR: CategoricalIndex and IntervalIndex are missing _index_data attribute
It looks like the `_index_data` attribute wasn't added to `CategoricalIndex` or `IntervalIndex`.  This leads to some regressions with `GroupBy.apply`.

Not sure what the fix should be, as there isn't a singular array that directly backs the underlying values for `CategoricalIndex` or `IntervalIndex`, so the approach used to add `_index_data` for other types doesn't look like it will work here.

Example of broken behavior on `master`:
```python
In [1]: import pandas as pd; pd.__version__
Out[1]: '1.0.0rc0+146.g6f395ad42'

In [2]: index = pd.CategoricalIndex(list("abc"))  
   ...: df = pd.DataFrame({"group": [0, 0, 1], "value": [1, 2, 3]}, index=index)

In [3]: df.groupby("group").apply(lambda x: x)
---------------------------------------------------------------------------
AttributeError: 'CategoricalIndex' object has no attribute '_index_data'

```

Same behavior worked on 0.25.3:
```python
In [1]: import pandas as pd; pd.__version__
Out[1]: '0.25.3'

In [2]: index = pd.CategoricalIndex(list("abc"))  
   ...: df = pd.DataFrame({"group": [0, 0, 1], "value": [1, 2, 3]}, index=index)

In [3]: df.groupby("group").apply(lambda x: x)
Out[3]: 
   group  value
a      0      1
b      0      2
c      1      3
```
Swapping `CategoricalIndex` with `IntervalIndex` results in the same behavior above.

### PR DESCRIPTION
**Pull request by jschendel**
- [X] closes #31223
- [X] closes #31248 
- [X] tests added / passed
- [X] passes `black pandas`
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

No whatsnew since this is a regression.

### CODE REVIEW

File: pandas/_libs/reduction.pyx [hunk 1]
```diff
@@ -158,7 +158,7 @@ cdef class _BaseGrouper:
         if util.is_array(values) and not values.flags.contiguous:
             # e.g. Categorical has no `flags` attribute
             values = values.copy()
-        index = dummy.index.values
+        index = dummy.index.to_numpy()
```
Comment (jbrockmendel) [inline pandas/_libs/reduction.pyx]: for EA cases, we want to avoid going through libreduction altogether

Comment (TomAugspurger) [reply pandas/_libs/reduction.pyx]: What do you mean? We shouldn't be hitting this code path in the first place?

Comment (jreback) [reply pandas/_libs/reduction.pyx]: hmm, yeah what does this do to the categorical grouping case. This should be a highly optimized path, is this still?

**Review by jreback — CHANGES_REQUESTED** [review]

File: pandas/_libs/reduction.pyx (hunk 1 above)
Comment (jbrockmendel) [reply pandas/_libs/reduction.pyx]: > What do you mean? We shouldn't be hitting this code path in the first place?

Correct.  This is called from core.apply.FrameApply.apply_standard after a check:

```
        if (
            self.result_type in ["reduce", None]
            and not self.dtypes.apply(is_extension_array_dtype).any()
            # Disallow complex_internals since libreduction shortcut
            #  cannot handle MultiIndex
            and not isinstance(self.agg_axis, ABCMultiIndex)
        ):
```

The MultiIndex check may need to be expanded to include EAs.

I think this is called from one other place in non-test code, so the missing check may belong there.

Comment (TomAugspurger) [reply pandas/_libs/reduction.pyx]: I vaguely recall a `_has_complex_...` property that indicated with the Index was backed by an ndarray. Was that removed?

Comment (jbrockmendel) [reply pandas/_libs/reduction.pyx]: `self._has_complex_internals` was equivalent to to `isinstance(self, MultiIndex)`

**Comment by jschendel** [comment]
Okay, I've added back `Index._has_complex_internals` but modified it to also be `True` for `CategoricalIndex`, `IntervalIndex`, and `PeriodIndex` since those indexes require (potentially expensive) conversion to get a numpy array of values.

File: pandas/_libs/reduction.pyx (hunk 1 above)
Comment (jschendel) [reply pandas/_libs/reduction.pyx]: The issue in question doesn't actually go through here, but rather `_aggregate_series_fast`, which dispatches through `libreduction`, but the point still applies that we want to avoid EA backed indexes here, so I've modified the check to use `_has_complex_internals`.

File: pandas/core/groupby/ops.py [hunk 2]
```diff
@@ -616,8 +616,8 @@ def agg_series(self, obj: Series, func):
             # TODO: can we get a performant workaround for EAs backed by ndarray?
             return self._aggregate_series_pure_python(obj, func)
 
-        elif isinstance(obj.index, MultiIndex):
-            # MultiIndex; Pre-empt TypeError in _aggregate_series_fast
+        elif obj.index._has_complex_internals:
```
Comment (jschendel) [inline pandas/core/groupby/ops.py]: This now excludes `PeriodIndex`, which previously worked fine since `.values` converted to a numpy array.  It looks more performant to exclude `PeriodIndex` though, since we avoid the conversion to numpy:
```python
In [1]: import numpy as np 
   ...: import pandas as pd 
   ...: from string import ascii_letters 
   ...:  
   ...: np.random.seed(123) 
   ...: group = np.random.choice(list(ascii_letters), 10**5) 
   ...: value = np.random.randint(12345, size=10**5) 
   ...: index = pd.period_range("2000", freq="D", periods=10**5) 
   ...: df = pd.DataFrame({"group": group, "value": value}, index=index)

In [2]: %timeit df.groupby("group").agg({"value": pd.Series.nunique})
17.8 ms ± 48.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)  # on this branch
95.9 ms ± 183 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)  # on master
```

**Comment by TomAugspurger** [comment]
@jreback I think this is fixing a regression. We should leave it on the 1.0.0 milestone.

**Comment by TomAugspurger** [comment]
Merged master to fix the CI failure.

**Comment by jschendel** [comment]
Added an additional check against `_has_complex_internals` that fixes #31248 and the associated test cases.

File: pandas/core/indexes/base.py [hunk 3]
```diff
@@ -4109,6 +4109,14 @@ def _assert_can_do_op(self, value):
         if not is_scalar(value):
             raise TypeError(f"'value' must be a scalar, passed: {type(value).__name__}")
 
+    @property
+    def _has_complex_internals(self):
+        """
+        Indicates if an index is not directly backed by a numpy array
+        """
+        # used to disable groupby tricks
```
Comment (jbrockmendel) [inline pandas/core/indexes/base.py]: "tricks" -> "going through libreduction fastpath which would ..."?

**Review by TomAugspurger — APPROVED** [review]
LGTM. Thanks @jschendel.

Merging later tonight if there aren't any objections.

File: pandas/core/indexes/base.py (hunk 3 above)
Comment (jschendel) [reply pandas/core/indexes/base.py]: Copied that from the original implementation but agree it's not very helpful. Updated to something that's more informative.

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks

**Comment by jreback** [comment]
@jschendel can you push a backport for this, didn't automatically work.
