### ISSUE TITLE
BUG: AttributeError: 'DataFrame' object has no attribute '_is_builtin_func'

### ISSUE THREAD

**Issue by ngupta23** [pandas-dev/pandas#42356]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Comes from private repo, but I will paste snippets where it gives errors
data.loc[:, 'update_status'] = data.apply(
    my_function,
    func_arg=some_value    
)
```

#### Problem description

GitHub Actions started failing after July 3rd (see image below). Realized that pandas has been upgraded to 1.3.0 on July 2nd. **Reverted to pinning pandas to <= 1.2.5 and it started working again.**

![image](https://user-images.githubusercontent.com/33585645/124355972-63949480-dbd9-11eb-8c61-ed9570883136.png)

#### Output of ``pd.show_versions()``

<details>

Issue with 1.3.0 but works fine with 1.2.5

</details>

**Comment by casperdcl** [comment]
looks like in 33fec602ffd this private function was exposed as `pandas.core.common.is_builtin_func()`

**Comment by phofl** [comment]
@ngupta23 is this solved then?

**Comment by casperdcl** [comment]
it's not a `pandas` bug. `pandas` deprecated a non-public method and created a public replacement. Yes should be closed.
