### ISSUE TITLE
BUG: Non-deterministic AttributeError exception accessing DataFrame columns

### ISSUE THREAD

**Issue by pvieito** [pandas-dev/pandas#40146]
#### Code Sample

```python
# Platform: Ubuntu 18.04.1 LTS
# Python: Python 3.8.7 (default, Dec 21 2020, 20:10:35) 
import pandas as pd
for i in range(100_000_000):
    df = pd.DataFrame.from_records([{"A": 1}])
    print(i, df)
    df.A  # Sometime it raises `AttributeError('DataFrame' object has no attribute 'A')` ?
```

#### Problem Description

Since we have updated to the last Pandas version 1.2.2 (from Pandas 0.25) we have been detecting some unexpected `AttributeError` exceptions when accessing `DataFrame` objects which do contain the accessed columns. We have detected this error in multiple projects, with different input data and with multiple column `dtype` types.

Also the errors seem to be non-deterministic and very difficult to reproduce (May be derived from some race condition? Memory issues?). I have tried multiple times to re-run the same exact process script with the same input data and environment and I could not replicate the error which seems to occur randomly. Since we have migrated to Pandas 1.2.2 a week ago we have detected this error 15 times (from the tens of thousands of DataFrame accesses we are doing daily in the processes).

#### Expected Output

Should not raise any `AttributeError` exception.

#### Output of ``pd.show_versions()``

Extracted from the error log of a production server when one of the exceptions occurred:

<details>

| Package        | Version           |
| -------------|---------------|
aiohttp | 3.7.3
amightygirl.paapi5-python-sdk | 1.0.0
appdirs | 1.4.4
argon2-cffi | 20.1.0
arrow | 0.14.7
async-generator | 1.10
async-timeout | 3.0.1
attrs | 20.3.0
babel | 2.9.0
backcall | 0.2.0
beautifulsoup4 | 4.9.3
bleach | 3.3.0
boto3 | 1.17.14
botocore | 1.20.14
cached-property | 1.5.2
cachetools | 4.2.1
certifi | 2020.12.5
cffi | 1.14.5
chardet | 3.0.4
click | 7.1.2
click-plugins | 1.1.1
cligj | 0.7.1
cloudpickle | 1.6.0
configparser | 5.0.1
curlify | 2.2.1
cycler | 0.10.0
dask | 2.5.0
datatools | INTERNAL
decorator | 4.4.2
defusedxml | 0.6.0
elasticsearch | 7.11.0
entrypoints | 0.3
facebook-business | 9.0.3
fiona | 1.8.18
fsspec | 0.8.5
furl | 2.1.0
future | 0.18.2
geopandas | 0.8.2
google-api-core | 1.26.0
google-api-python-client | 1.12.8
google-auth | 1.27.0
google-auth-httplib2 | 0.0.4
google-auth-oauthlib | 0.4.2
googleads | 26.0.0
googleapis-common-protos | 1.52.0
httplib2 | 0.19.0
ics | 0.7
idna | 2.10
ipykernel | 5.4.3
ipython | 7.20.0
ipython-genutils | 0.2.0
ipywidgets | 7.6.3
isodate | 0.6.0
jedi | 0.18.0
jinja2 | 2.11.3
jmespath | 0.10.0
joblib | 1.0.1
jsonschema | 3.2.0
jupyter | 1.0.0
jupyter-client | 6.1.11
jupyter-console | 6.2.0
jupyter-core | 4.7.1
jupyterlab-pygments | 0.1.2
jupyterlab-widgets | 1.0.0
keplergl | 0.2.2
kiwisolver | 1.3.1
limits | 1.5.1
locket | 0.2.1
lxml | 4.6.2
markupsafe | 1.1.1
matplotlib | 3.3.4
mistune | 0.8.4
multi-key-dict | 2.0.3
multidict | 5.1.0
munch | 2.5.0
nbclient | 0.5.2
nbconvert | 6.0.7
nbformat | 5.1.2
nest-asyncio | 1.5.1
netaddr | 0.8.0
notebook | 6.2.0
numpy | 1.18.5
oauth2client | 4.1.3
oauthlib | 3.1.0
orderedmultidict | 1.0.1
packaging | 20.9
pandas | 1.2.2
pandocfilters | 1.4.3
parso | 0.8.1
partd | 1.1.0
pbr | 5.5.1
pexpect | 4.8.0
pickleshare | 0.7.5
pika | 1.2.0
pillow | 8.1.0
pip | 21.0.1
pkg-resources | 0.0.0
plotly | 3.10.0
polygon-geohasher | 0.0.1
prometheus-client | 0.9.0
prompt-toolkit | 3.0.16
protobuf | 3.14.0
psutil | 5.8.0
psycopg2-binary | 2.8.6
ptyprocess | 0.7.0
pyasn1 | 0.4.8
pyasn1-modules | 0.2.8
pycountry | 20.7.3
pycparser | 2.20
pycryptodome | 3.10.1
pygments | 2.8.0
pyhive | 0.6.3
pylogbeat | 2.0.0
pyodbc | 4.0.30
pyparsing | 2.4.7
pyproj | 3.0.0.post1
pyrsistent | 0.17.3
python-dateutil | 2.8.1
python-geohash | 0.8.5
python-jenkins | 1.7.0
python-logstash-async | 2.2.0
pytz | 2021.1
pyxdameraulevenshtein | 1.7.0
pyyaml | 5.4.1
pyzmq | 22.0.3
qtconsole | 5.0.2
qtpy | 1.9.0
redis | 3.5.3
requests | 2.25.1
requests-file | 1.5.1
requests-oauthlib | 1.3.0
requests-toolbelt | 0.9.1
requirements-parser | 0.2.0
retrying | 1.3.3
rsa | 4.7.1
rtree | 0.9.7
s3transfer | 0.3.4
scikit-surprise | 1.0.6
scipy | 1.5.4
seaborn | 0.11.1
send2trash | 1.5.0
sentry-sdk | 0.20.3
setuptools | 53.0.0
shapely | 1.7.1
six | 1.15.0
soupsieve | 2.2
sqlalchemy | 1.3.23
stringcase | 1.2.0
tatsu | 5.5.0
terminado | 0.9.2
testpath | 0.4.4
toolz | 0.11.1
tornado | 6.1
traitlets | 5.0.5
traittypes | 0.2.1
twitter-ads | 8.0.0
typing-extensions | 3.7.4.3
tzlocal | 2.1
uritemplate | 3.0.1
urllib3 | 1.26.3
wcwidth | 0.2.5
webencodings | 0.5.1
widgetsnbextension | 3.5.1
wordcloud | 1.8.1
xlrd | 2.0.1
xmltodict | 0.12.0
yarl | 1.6.3
zeep | 4.0.0
</details>

**Comment by rhshadrach** [comment]
Has the issue ever been observed using the example provided, or has it only been observed with production code?

**Comment by pvieito** [comment]
Hi, no, only in the production code. But I have added more logs to ensure this is a real issue:

#### Code Snippet

This is a verbatim code snippet of one of the the production code functions that have been failing with this error:

```
def get_filtered_feature_weights_from_s3(*, model_entity, model_type, model_name):
    weights_df = models.get_model_weights_parameters_from_s3()
    logging.info(f"Processing feature weights from table (columns: {list(weights_df.columns)}):\n{weights_df}")
    weights_mask = \
        (weights_df.ModelEntity == model_entity) & \
        (weights_df.ModelName == model_name) & \
        (weights_df.ModelType == model_type) & \
        (weights_df.Status == 1)
    filtered_weights_df = weights_df[weights_mask].copy()
    return filtered_weights_df
```

It randomly fails when accessing the first column `ModelEntity` with this error:

```
AttributeError("'DataFrame' object has no attribute 'ModelEntity'")
```

With this traceback:

```
AttributeError: 'DataFrame' object has no attribute 'ModelEntity'
  File "DataTools/Modules/iteration_core.py", line 428, in _run_iteration
    result = callable_function(**callable_kwargs)
  File "DataTools/Modules/internal_support.py", line 419, in decorated_internal_function
    return _check_and_call_function(
  File "DataTools/Modules/internal_support.py", line 394, in _check_and_call_function
    return _call_function(
  File "DataTools/Modules/internal_support.py", line 328, in _call_function
    return function(*args, **kwargs)
  File "DataTools/Modules/pipeline_support.py", line 413, in _run_etl_pipeline_iteration
    etl_pipeline._transform(**full_kwargs)
  File "DataTools/Modules/internal_support.py", line 419, in decorated_internal_function
    return _check_and_call_function(
  File "DataTools/Modules/internal_support.py", line 394, in _check_and_call_function
    return _call_function(
  File "DataTools/Modules/internal_support.py", line 328, in _call_function
    return function(*args, **kwargs)
  File "DataTools/Modules/pipeline_support.py", line 251, in _transform
    df = operation_core._execute_transform_operation(
  File "DataTools/Modules/internal_support.py", line 419, in decorated_internal_function
    return _check_and_call_function(
  File "DataTools/Modules/internal_support.py", line 394, in _check_and_call_function
    return _call_function(
  File "DataTools/Modules/internal_support.py", line 328, in _call_function
    return function(*args, **kwargs)
  File "DataTools/Modules/operation_core.py", line 39, in _execute_transform_operation
    return operation_module.transform(df, **kwargs)
  File "tmp/AD5E94F4-7EB6-491D-86BC-FB547286D609/732E108C-6B95-4799-A804-299656A9B58E/13706/Profiling/Operations/Scores/Article.py", line 49, in transform
    df = article.compute_article_scores(
  File "Modules/Scores/article.py", line 132, in compute_article_scores
    feature_weights_df = features.get_filtered_feature_weights_dataframe(
  File "Modules/Models/features.py", line 22, in get_filtered_feature_weights_dataframe
    weights_df = get_filtered_feature_weights_from_s3(
  File "Modules/Models/features.py", line 12, in get_filtered_feature_weights_from_s3
    (weights_df.ModelEntity == model_entity) & \
```

#### Logs

As we have added that extra logging line before the column access we can now ensure this is a real problem:

```
Timestamp: 2021-03-03 06:02:45
Level: INFO
Message:
Processing feature weights from table (columns: ['ModelEntity', 'ModelType', 'ModelName', 'ModelIdentifier', 'Key', 'Status', 'RawValue', 'Value']):
ModelEntity        ModelType        ModelName  ... Status RawValue     Value
0       Article  ArticleBargains  ContentBased_v1  ...      1     16.0  0.093897 1       Article  ArticleBargains  ContentBased_v1  ...
1      6.0  0.035211 2       Article  ArticleBargains  ContentBased_v1  ...      1     10.0  0.058685 3       Article  ArticleBargains  C...
---
Timestamp: 2021-03-03 06:02:45
Level: ERROR
Message:
AttributeError: 'DataFrame' object has no attribute 'ModelEntity'
```

As you can see `ModelEntity` is indeed in the `DataFrame` just before accessing it.

**Comment by rhshadrach** [comment]
Thanks for the information. Since the DataFrame exists and you are merely accessing a column on it, I'd guess this isn't a memory issue. You mention a possible race-condition, is this being run via multithreading or multiprocessing?

**Comment by pvieito** [comment]
Yes, we are using multithreading with [`joblib`](https://joblib.readthedocs.io/en/latest/) and the [`loky`](https://github.com/tomMoral/loky) backend. But we do not modify that `DataFrame` in any point of the code, and the errors have only started appearing after upgrading from Pandas 0.25 to 1.2.

**Comment by jreback** [comment]
DataFrames are not generally threadsafe even for copying. you should use multiprocessing.

**Comment by pvieito** [comment]
The `loky` backend of `joblib` is a multiprocessing backend (ie. is spawns a new process for each "thread"). So that should not be a problem in my opinion.

**Comment by rhshadrach** [comment]
@pvieito: Even `df.sum()` can modify the internals of a DataFrame.

**Comment by jbrockmendel** [comment]
We see this in the CI occasinally

**Comment by MarcoGorelli** [comment]
> We see this in the CI occasinally

Do you remember when (if the job's not too old and the logs are still there)? If not, I'm not sure what can be done here

**Comment by mroeschke** [comment]
Since this issue doesn't seem to be actionable, closing but can reopen if I misunderstood
