### ISSUE TITLE
BUG: Pandas + gcsfs regression

### ISSUE THREAD

**Issue by gfelot** [pandas-dev/pandas#40833]
#### Problem description

I'm use to fix pandas lib up to the minor number (i.e pandas=1.1).

All my work is on Google Cloud Storage so I use a lot

`df = pd.read_csv(gcs+path)`

My old script use a mix of `pandas=1.1` and `gcsfs=0.7`
On a previous version of a script I work with pandas 1.1.5 and gcsfs 0.7.1

After an update the script was build (docker image) with gcsfs 0.7.2 where I got this error on read_csv
```
Traceback (most recent call last):
  File "/.../python3.7/site-packages/aiohttp/client.py", line 326, in __del__
    if not self.closed:
  File "/.../python3.7/site-packages/aiohttp/client.py", line 963, in closed
    return self._connector is None or self._connector.closed
AttributeError: 'ClientSession' object has no attribute '_connector'
```

I couldn't fix it but a simple revert back to 0.7.1 make it work.

I also tried to use the last version 0.8.0 and I needed to install manually a dependency after a fail. It was `ujson`.

I don't know if it's a pandas or a gcsfs regression but at least I wanted to write it somewhere if anyone face the same issue.

**Comment by jorisvandenbossche** [comment]
Since the problem occurred after an update of `gcsfs`, it might rather be an issue with `gcsfs`. And checking their issues, this might be the same as https://github.com/dask/gcsfs/issues/373

**Comment by jorisvandenbossche** [comment]
@gfelot I am going to close this issue, as there is no action to take for pandas. But please follow-up on https://github.com/dask/gcsfs/issues/373 if you still have problems with it.
