### ISSUE TITLE
BUG: import error with python>=3.6.x since 0.23.0

### ISSUE THREAD

**Issue by minggli** [pandas-dev/pandas#25341]
#### Code Sample, a copy-pastable example if possible

```python
import sys
print(sys.version)

import pandas as pd
```

#### Problem description

It appears to work fine on python 3.5.5 but not on 3.6.5 or 3.7.0

```python
3.7.0 (default, Jul  6 2018, 14:29:43)
[Clang 9.0.0 (clang-900.0.39.2)]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mingli/.virtualenvs/test/lib/python3.7/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "/Users/mingli/.virtualenvs/test/lib/python3.7/site-packages/pandas/compat/__init__.py", line 447, in <module>
    re_type = typing.re.Pattern
AttributeError: module 'typing' has no attribute 're'
```

#### Expected Output

```python
3.7.0 (default, Jul  6 2018, 14:29:43)
[Clang 9.0.0 (clang-900.0.39.2)]
```

**Comment by minggli** [comment]
closed as it is due to a local file named as `typing.py` 🙁 🤦‍♂️

**Comment by mlissner** [comment]
For any others arriving here, in certain version so Python, you seem to need to do `from typing import Pattern`, `some_var: Pattern = xxx` instead of doing `from typing import re` and then `some_var: re.Pattern`. At least, this is what made mypy happy for me today.
