### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by bharat-ics** [pandas-dev/pandas#38999]
- [Checked ] I have checked that this issue has not already been reported.

- [ Checked] I have confirmed this bug exists on the latest version of pandas.

- [Not Checked ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
df.to_csv("test.csv")

ImportError: cannot import name 'CompressionOptions' from 'pandas._typing
```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

Breaking error on printing csvs right after upgrading to 1.1.5

#### Expected Output
CSV output of dataframe

**Comment by vangorade** [comment]
please add  reproducible example and version of pandas you are using

**Comment by hollypeter** [comment]
Meet same issue. 
have you try restart Kernel? mine works after restart

**Comment by simonjayhawkins** [comment]
> please add reproducible example and version of pandas you are using

closing. feel free to open a new issue with a reproducible example. see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
