### PR TITLE
COMPAT: NaT accessors

### LINKED ISSUE #15781: Return value of boolean datetime fields of NaT: False or NaN ?
From discussion in https://github.com/pandas-dev/pandas/pull/15589, the handling of NaT is different for different datetime fields.

On a scalar value, `is_leap_year` returns False, the others are not defined:

```
In [1]: pd.Timestamp('NaT').is_month_start
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-654cc4e613aa> in <module>()
----> 1 pd.Timestamp('NaT').is_month_start

AttributeError: 'NaTType' object has no attribute 'is_month_start'

In [2]: pd.Timestamp('NaT').is_leap_year
Out[2]: False
```

On an index (or series `.dt` accessor), `is_leap_year` returns False, the others propagate NaN (with the consequence it is no longer a boolean array/series):

```
In [3]: pd.DatetimeIndex(['2012-01-01', 'NaT']).is_month_start
Out[3]: array([  1.,  nan])

In [4]: pd.DatetimeIndex(['2012-01-01', 'NaT']).is_leap_year
Out[4]: array([ True, False], dtype=bool)
```

So when `is_leap_year` was introduced in #13739, this was done on purpose, citing @sinhrks "pd.NaT.is_leap_year results in False, as I think users want bool array.".

This seems indeed the more logical thing to return (certainly for arrays/series), so you can eg use it for indexing. For scalars it is a bit less clear what is the preferable option (return False or NaN), but probably best to be consistent.

### PR DESCRIPTION
**Pull request by jreback**
closes #15781

PR
```
In [1]: idx = DatetimeIndex(['1/1/2000', None, None, '1/4/2000'])

In [2]: idx.is_month_start
Out[2]: array([ True, False, False, False], dtype=bool)

In [3]: idx.is_leap_year
Out[3]: array([ True, False, False,  True], dtype=bool)
```

0.19.2
```
In [1]: idx = DatetimeIndex(['1/1/2000', None, None, '1/4/2000'])

In [3]: idx.is_month_start
Out[3]: array([  1.,  nan,  nan,   0.])

In [2]: idx.is_leap_year
Out[2]: array([ True, False, False,  True], dtype=bool)

```
mimics ``is_leap_year`` to return a boolean (inlcuding for ``NaT``).

### CODE REVIEW

**Comment by jreback** [comment]
not ready yet.

```
In [1]: idx = DatetimeIndex(['1/1/2000', None, None, '1/4/2000'])

In [2]: idx.is_month_start
Out[2]: array([ True, False, False, False], dtype=bool)

In [3]: idx.is_leap_year
Out[3]: array([ True, False, False,  True], dtype=bool)
```

File: pandas/tests/scalar/test_timestamp.py [hunk 1]
```diff
@@ -579,47 +587,42 @@ def check(value, equal):
...
+            result = getattr(NaT, field)
+            assert np.isnan(result)
+
+            result = getattr(ts, field)
+            assert np.isnan(result)
+
+        for field in self._bool_accessors:
+
+            result = getattr(NaT, field)
+            assert not result
```
Comment (jorisvandenbossche) [inline pandas/tests/scalar/test_timestamp.py]: `assert result is False` 
In the bare assert style for pytest, I find that a bit clearer if you are explicitly testing for False, and in this case, more importantly, otherwise 0 would pass the test (eg if for some reason the result if converted to float which is what happens in the current code)

Comment (jreback) [inline pandas/tests/scalar/test_timestamp.py]: yep fixed

**Comment by jreback** [comment]
@jorisvandenbossche

**Comment by jreback** [comment]
any comments?

**Review by jorisvandenbossche — APPROVED** [review]
Looks good!
