### PR TITLE
fix is_scalar documentation (#28998)

### LINKED ISSUE #28998: Documentation bug in pandas.api.types.is_scalar
#### Example

The first example is:

```
>>> dt = pd.datetime.datetime(2018, 10, 3)
>>> pd.is_scalar(dt)
True
```
#### Problem description

`is_scalar` is not a member of `pd`:

```
AttributeError: module 'pandas' has no attribute 'is_scalar'
```

#### Expected

`pd.api.types.is_scalar(...)`

### PR DESCRIPTION
**Pull request by andreasbuhr**
- [x] closes #28998
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

is_scalar documentation was wrong, see #28998

### CODE REVIEW

**Comment by moi90** [comment]
I was about to do the same... ^^

**Review by WillAyd — APPROVED** [review]
lgtm. We are working on a release of 0.25.2 today so this might sit for a bit, but I don't think changes are required unless anyone else disagrees

**Comment by TomAugspurger** [comment]
@WillAyd no harm in merging to master since this is going in 1.0.

**Comment by TomAugspurger** [comment]
Thanks @andreasbuhr!
