### ISSUE TITLE
excel header_style broken in 0.22

### ISSUE THREAD

**Issue by gordol** [pandas-dev/pandas#19386]
```python
import pandas as pd
pd.io.formats.excel.header_style = None
```

After updating, it is no longer possible to override the excel header styles.

Previously, this was possible in 0.19.2:

`pd.formats.format.header_style = None`

It seems header_style has been moving around constantly lately... Can we please put it somewhere and leave it there??? Or, if it's going to be moved constantly, it should live on a private module path. I realize python doesn't have private scoping, but there are paths in the pandas module that are privately scoped, by convention, yet don't follow the standard python convention of underscoring the names.

How are we supposed to accomplish the removal of styles on the latest build?

That module path DOES indeed exist... but something is wonky with the imports, it seems.

Exception is raised:
`AttributeError: 'module' object has no attribute 'excel' `

Possibly related? https://github.com/pandas-dev/pandas/pull/15530

**Comment by chris-b1** [comment]
For me this does work on `0.22` to remove the header styling
```
pd.io.formats.excel.header_style = None
```

But in any case, this wasn't intended to public - I do think it would be reasonable enhancement to add an argument to `DataFrame.to_excel` to handle this case if you're interested in doing a PR?

**Comment by gordol** [comment]
Hmm...

I wonder why it's not working for me... Like I said, I can clearly see the module in my local path, and can see that line in the module... but it refuses to load.

Would that be added here? https://github.com/pandas-dev/pandas/blob/a9d8e04ab68f688f899b4164bfa1ac868c9c1c64/pandas/core/frame.py#L1555

I'm not sure... looks like there's some kind of new styling module, and I'm totally lost as to where to even start... It probably supports what I need, but there's not much documentation on this (it's listed as experimental in the docs) https://github.com/pandas-dev/pandas/blob/a9d8e04ab68f688f899b4164bfa1ac868c9c1c64/pandas/io/formats/style.py#L160

**Comment by gordol** [comment]
Honestly, that looks like totally redundant code...

**Comment by gordol** [comment]
I'm okay with removing *all* styles... even. It doesn't even have to be just the headers.

**Comment by chris-b1** [comment]
Ah I was forgetting about the styler enhancements, if you really want no styles, easy enough solution is `df.style.to_excel('output.xlsx')`

**Comment by WillAyd** [comment]
You should be able to override this now via https://github.com/pandas-dev/pandas/pull/22759

**Comment by yyz20002008** [comment]
@WillAyd 
Hello 
Currently header has a border and bolded.  I don't want header has any format after it is converted to excel, then I used 
`df.io.formats.excel.header_style = None` 
Error was poped out:
`AttributeError: 'DataFrame' object has no attribute 'io'`
 Then I saw 
`df.io.formats.excel.header_style = None` doesn't work anymore since 0.24 from [https://stackoverflow.com/questions/36694313/pandas-xlsxwriter-format-header](Link)

I saw your response, but I still didn't see any solution in #22759

Do you have any idea how to remove header format?

**Comment by WillAyd** [comment]
There isn't a currently exposed way of doing this. #25185 is open if you'd like to take a look and contribute something on that front

**Comment by Diegostastico** [comment]
From version 0.24 (Jan 25, 2019) this is now required:

import pandas.io.formats.excel
pandas.io.formats.excel.ExcelFormatter.header_style = None

currently still working for pandas version 1.2.4 (Apr 12, 2021)
