### ISSUE TITLE
Series.apply fails when the series is a timezone aware datetime

### ISSUE THREAD

**Issue by goriccardo** [pandas-dev/pandas#25959]
To reproduce the problem:
```python
import pandas as pd

s = pd.util.testing.makeTimeSeries()
s = s.tz_localize('UTC')
pd.Series(s.index).apply(lambda x: pd.Series([1,2]))

AttributeError: 'PandasArray' object has no attribute 'tolist'
```
It works fine if the function to apply returns a scalar instead of a Series:

```python
import pandas as pd

s = pd.util.testing.makeTimeSeries()
s = s.tz_localize('UTC')
pd.Series(s.index).apply(lambda x: 1)
```
or it there is no timezone information in the series.
```python
import pandas as pd

s = pd.util.testing.makeTimeSeries()
pd.Series(s.index).apply(lambda x: pd.Series([1,2]))
```
The issue is present with pandas 0.24.2, it used to work fine with 0.23.4.

**Comment by ThomasKluiters** [comment]
I'd like to pick this up as my first issue to contribute to this repo :)

**Comment by jbrockmendel** [comment]
One more reason EAs should have “tolist” cc @jreback @jorisvandenbossche

**Comment by ThomasKluiters** [comment]
Then would the better fix be to just implement tolist for extension arrays?

**Comment by jbrockmendel** [comment]
Implementing tolist can wait for now.
