### ISSUE TITLE
CI allowed failure - TestReadHtml.test_thousands_macau_index_col[bs4]

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#28125]
```
=================================== FAILURES ===================================
_______________ TestReadHtml.test_thousands_macau_index_col[bs4] _______________
[gw1] linux -- Python 3.6.9 /home/travis/miniconda3/envs/pandas-dev/bin/python
self = <pandas.tests.io.test_html.TestReadHtml object at 0x7f11591bf5c0>
datapath = <function datapath.<locals>.deco at 0x7f1157bd3a60>
    @pytest.mark.slow
    def test_thousands_macau_index_col(self, datapath):
        all_non_nan_table_index = -2
        macau_data = datapath("io", "data", "macau.html")
>       dfs = self.read_html(macau_data, index_col=0, header=0)
pandas/tests/io/test_html.py:389: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pandas/io/html.py:1095: in read_html
    displayed_only=displayed_only,
pandas/io/html.py:912: in _parse
    raise_with_traceback(retained)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
exc = AttributeError("'NoneType' object has no attribute 'items'",)
traceback = None
    def raise_with_traceback(exc, traceback=Ellipsis):
        """
        Raise exception with existing traceback.
        If traceback is not passed, uses sys.exc_info() to get traceback.
        """
        if traceback == Ellipsis:
            _, _, traceback = sys.exc_info()
>       raise exc.with_traceback(traceback)
E       AttributeError: 'NoneType' object has no attribute 'items'
pandas/compat/__init__.py:46: AttributeError
```

It appears that this started failing with #27962

cc @jbrockmendel

**Comment by simonjayhawkins** [comment]
probably not due to #27962,  several changes in dependencies..

```
11c11
< beautifulsoup4            4.8.0                    py36_0
---
> beautifulsoup4            4.7.1                    py36_1
26c26
< cython                    0.29.13          py36he6710b0_0
---
> cython                    0.29.12          py36he6710b0_0
71c71
< lxml                      4.4.1            py36hefd8a0e_0
---
> lxml                      4.3.4            py36hefd8a0e_0
84c84
< numexpr                   2.7.0            py36h9e4a6bb_0
---
> numexpr                   2.6.9            py36h9e4a6bb_0
90c90
< pandas                    0.25.0+199.gbe08902a7           dev_0    <develop>
---
> pandas                    0.25.0+198.g325dd686d           dev_0    <develop>
93c93
< pip                       19.2.2                   py36_0
---
> pip                       19.1.1                   py36_0
114c114
< pyyaml                    5.1.2            py36h7b6447c_0
---
> pyyaml                    5.1.1            py36h7b6447c_0
121c121
< scipy                     1.3.1            py36h7c811a0_0
---
> scipy                     1.3.0            py36h7c811a0_0
127c127
< sqlalchemy                1.3.7            py36h7b6447c_0
---
> sqlalchemy                1.3.5            py36h7b6447c_0
135c135
< werkzeug                  0.15.5                     py_0
---
> werkzeug                  0.15.4                     py_0
```

**Comment by simonjayhawkins** [comment]
https://travis-ci.org/pandas-dev/pandas/jobs/576942064

**Comment by TomAugspurger** [comment]
Ahh, it's an allowed failure. Thanks.

**Comment by simonjayhawkins** [comment]
closing in favor of #29622
