### PR TITLE
REF: lazify relativedelta imports

### PR DESCRIPTION
**Pull request by jbrockmendel**
In most cases we don't need it, so delay importing it until we do.

in io.stata it can be replaced with datetime.timedelta.  In the plotting code I _think_ it can be replaced with `tot_secs = (dmax-dmin).total_seconds()`, need to track down why that wasn't done in the first place.

### CODE REVIEW

File: pandas/_libs/tslibs/parsing.pyx [hunk 1]
```diff
@@ -692,6 +691,9 @@ cdef datetime dateutil_parse(
         ) from err
 
     if res.weekday is not None and not res.day:
+        assert False
```
Comment (jbrockmendel) [inline pandas/_libs/tslibs/parsing.pyx:694]: woops, this wasn't supposed to make it into the PR.  looks like we don't get here in the tests.  And its a good thing, because L696 should just be `relativedelta(...)`, not `relativedelta.relativedelta(...)`

File: pandas/plotting/_matplotlib/converter.py [hunk 2]
```diff
@@ -349,6 +348,8 @@ def __init__(self, locator, tz=None, defaultfmt: str = "%Y-%m-%d") -> None:
 class PandasAutoDateLocator(mdates.AutoDateLocator):
     def get_locator(self, dmin, dmax):
         """Pick the best locator based on a distance."""
+        from dateutil.relativedelta import relativedelta
+
         delta = relativedelta(dmax, dmin)
```
Comment (jbrockmendel) [inline pandas/plotting/_matplotlib/converter.py:353]: seems to me that on L357 we could do `tot_sec = (dmax - dmin).total_seconds()`.  Doing that doesn't break any of our tests.  the relativedelta usage was introduced in https://github.com/pandas-dev/pandas/commit/367e98177573e3cabb712622621088cd193bbdec and i dont see any discussion of why total_seconds wouldn't work.

File: pandas/_libs/tslibs/parsing.pyx (hunk 1 above)
Comment (jbrockmendel) [reply pandas/_libs/tslibs/parsing.pyx:694]: should we just deprecate this case since it isnt reached and would raise if it ever were?

Comment (mroeschke) [reply pandas/_libs/tslibs/parsing.pyx:694]: This branch is always false because `res.day` is never 0 right?

File: pandas/plotting/_matplotlib/converter.py (hunk 2 above)
Comment (mroeschke) [reply pandas/plotting/_matplotlib/converter.py:353]: Yeah agreed seems `total_seconds()` should work here

File: pandas/_libs/tslibs/parsing.pyx (hunk 1 above)
Comment (jbrockmendel) [reply pandas/_libs/tslibs/parsing.pyx:694]: just never reached in tests.  `pd.Timestamp("2023 Sept Thu")` will hit this and raise `AttributeError: type object 'relativedelta' has no attribute 'relativedelta'` in main

Comment (jbrockmendel) [reply pandas/_libs/tslibs/parsing.pyx:694]: `ret` is a datetime object here, `res` is a `parser.parser._result` object

If we disable this check entirely then `pd.Timestamp("2023 Sept Thu")` behaves like `Timestamp("2023-09-01")` but I'm pretty sure if i run it tomorrow it will be 2023-09-02.  Rather than skip this block entirely, I'd prefer to change it to raise intentionally.

Comment (mroeschke) [reply pandas/_libs/tslibs/parsing.pyx:694]: Okay I think raising is reasonable as this format is a big ambiguous.

**Comment by jbrockmendel** [comment]
Updated to intentionally raise

**Review by mroeschke — APPROVED** [review]

File: pandas/plotting/_matplotlib/converter.py [hunk 3]
```diff
@@ -349,11 +348,7 @@ def __init__(self, locator, tz=None, defaultfmt: str = "%Y-%m-%d") -> None:
 class PandasAutoDateLocator(mdates.AutoDateLocator):
     def get_locator(self, dmin, dmax):
         """Pick the best locator based on a distance."""
-        delta = relativedelta(dmax, dmin)
-
-        num_days = (delta.years * 12.0 + delta.months) * 31.0 + delta.days
-        num_sec = (delta.hours * 60.0 + delta.minutes) * 60.0 + delta.seconds
-        tot_sec = num_days * 86400.0 + num_sec
+        tot_sec = (dmax - dmin).total_seconds()
```
Comment (MarcoGorelli) [inline pandas/plotting/_matplotlib/converter.py:351]: this looks much better, and avoids the approximations (e.g. all months have 31 days) from the original

File: pandas/tests/scalar/timestamp/test_constructors.py [hunk 4]
```diff
@@ -25,6 +25,12 @@
 
 
 class TestTimestampConstructors:
+    def test_weekday_but_no_day_raises(self):
+        # GH#52659
+        msg = "Parsing datetimes with weekday but no day information is not supported"
+        with pytest.raises(ValueError, match=msg):
+            Timestamp("2023 Sept Thu")
```
Comment (MarcoGorelli) [inline pandas/tests/scalar/timestamp/test_constructors.py:32]: how did this even work in the first place? 🤦

**Review by MarcoGorelli — APPROVED** [review]
+1, seems like a net positive

**Comment by MarcoGorelli** [comment]
> In the plotting code I _think_ it can be replaced with `tot_secs = (dmax-dmin).total_seconds()`, need to track down why that wasn't done in the first place.

the original comes from https://github.com/pandas-dev/pandas/pull/1616/commits/d0d15b0fa69a0d464a939b757a104d57fc7b4d58, but there's no context and looks like an initial oversight to me

**Comment by mroeschke** [comment]
Thanks @jbrockmendel
