### ISSUE TITLE
QST:TypeError: sum() got an unexpected keyword argument 'skipna'

### ISSUE THREAD

**Issue by zanwar369** [pandas-dev/pandas#35616]
Got the following error when trying to run a groupby sum after updating to the latest pandas:
TypeError: sum() got an unexpected keyword argument 'skipna'

->for row in Holdings[Holdings.Date>HP].groupby(['a','b','c']).sum(skipna=False)[['Balance','Withdrawal']:
....

**Comment by karuppiah7890** [comment]
I just checked the `help` like this

```python
>>> import pandas
>>> pandas.__version__
'1.1.0'
>>> help(pandas.core.groupby.generic.DataFrameGroupBy.sum)
```

and got

```bash
Help on function sum in module pandas.core.groupby.groupby:

sum(self, numeric_only: bool = True, min_count: int = 0)
    Compute sum of group values.

    Parameters
    ----------
    numeric_only : bool, default True
        Include only float, int, boolean columns. If None, will attempt to use
        everything, then use only numeric data.
    min_count : int, default 0
        The required number of valid values to perform the operation. If fewer
        than ``min_count`` non-NA values are present the result will be NA.

    Returns
    -------
    Series or DataFrame
        Computed sum of values within each group.
```

Looks like `skipna` is indeed an invalid / unexpected keyword argument.

Web docs reference - https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.GroupBy.sum.html

**Comment by karuppiah7890** [comment]
@zanwar369 ^

**Comment by zanwar369** [comment]
> I just checked the `help` like this
> 
> ```python
> >>> import pandas
> >>> pandas.__version__
> '1.1.0'
> >>> help(pandas.core.groupby.generic.DataFrameGroupBy.sum)
> ```
> 
> and got
> 
> ```shell
> Help on function sum in module pandas.core.groupby.groupby:
> 
> sum(self, numeric_only: bool = True, min_count: int = 0)
>     Compute sum of group values.
> 
>     Parameters
>     ----------
>     numeric_only : bool, default True
>         Include only float, int, boolean columns. If None, will attempt to use
>         everything, then use only numeric data.
>     min_count : int, default 0
>         The required number of valid values to perform the operation. If fewer
>         than ``min_count`` non-NA values are present the result will be NA.
> 
>     Returns
>     -------
>     Series or DataFrame
>         Computed sum of values within each group.
> ```
> 
> Looks like `skipna` is indeed an invalid / unexpected keyword argument. So, seems like a valid error. I also noticed that `skipna` didn't exist before too, in the argument list, when I checked version [1.0.0 docs](https://pandas.pydata.org/pandas-docs/version/1.0.0/reference/api/pandas.core.groupby.GroupBy.sum.html) and even the [oldest docs from 0.20.3](https://pandas.pydata.org/pandas-docs/version/0.20.3/generated/pandas.core.groupby.GroupBy.sum.html)
> 
> Web docs reference - https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.GroupBy.sum.html

Hmm interesting--thank you! Does anyone know why this was removed? It was functioning in previous versions perfectly

**Comment by karuppiah7890** [comment]
That's weird. I don't know, it feels like the previous versions didn't have this. Could you tell which version you used that had this? So that it can be confirmed? Maybe the docs just didn't reflect what was in the code

**Comment by zanwar369** [comment]
Sorry for the delay-- it works perfectly on 0.25.3
Looks like it stopped in version 1.0.0. i was utilizing this since I noticed a distinct difference in sums, for very large calculations with and without this qualifier.

**Comment by karuppiah7890** [comment]
Ah okay

**Comment by simonjayhawkins** [comment]
Thanks @zanwar369 for the question. I think is is covered by #29481, see https://github.com/pandas-dev/pandas/issues/29481#issuecomment-652647458 for a workaround

**Comment by zanwar369** [comment]
> Thanks @zanwar369 for the question. I think is is covered by #29481, see [#29481 (comment)](https://github.com/pandas-dev/pandas/issues/29481#issuecomment-652647458) for a workaround

Is there an actual fix in the works? Confused as to why it was removed in the first place

**Comment by jorisvandenbossche** [comment]
The underlying issue here is that the `skipna` keyword is at the moment not yet implemented for `groupby` reductions like `groupby(..).sum()`. 

It might be that before this keyword was ignored and recently started to raise, but it never actually worked (or was never documented).

The improvement to add `skipna` to the grouped reductions is covered in https://github.com/pandas-dev/pandas/issues/15675, so going to close this issues.

**Comment by jorisvandenbossche** [comment]
Duplicate of #15675
