### PR TITLE
REF/DEPR: Deprecate AbstractMethodError

### LINKED ISSUE #48909: Mark methods raising AbstractMethodError as abstractmethods?
Many methods raise `AbstractMethodError` instead of being an `abstractmethod`. Based on #20363 and #19268 it seems that there might be a performance issue with inheriting from `abc.ABC`:

> This class does not inherit from 'abc.ABCMeta' for performance reasons.

I didn't find a reference of why inheriting from `abc.ABC` is slow. Is that a python 2 thing? Would it make sense to use `abc.ABC+abstractmethod` instead of raising `AbstractMethodError`?

### PR DESCRIPTION
**Pull request by twoertwein**
closes #48909

Probably would need a whatsnew entry, for people inheriting from those now abstract classes. I'll keep this PR as a draft until I replaced all  cases of `AbstractMethodError` (that are actually implemented).

### CODE REVIEW

**Comment by mroeschke** [comment]
Just a reminder to please run the ASVs just to ensure there is no perf hit as mentioned in the original issue

**Comment by twoertwein** [comment]
I was able to avoid ASV until now :) Can I compare two ASV runs on python 3.10 (that's the only one I have installed):

> $ asv continuous -f 1.1 -E virtualenv upstream/main HEAD
> · No executable found for python 3.8
> · No environments selected
> $ asv continuous -f 1.1 -E existing upstream/main HEAD
> · No range spec may be specified if benchmarking in an existing environment

**Comment by mroeschke** [comment]
Still interested in this @twoertwein?

**Comment by twoertwein** [comment]
> Still interested in this @twoertwein?

Ready for review now :)

File: pandas/tests/extension/test_common.py [hunk 1]
```diff
@@ -6,14 +6,13 @@
 
 import pandas as pd
 import pandas._testing as tm
-from pandas.core.arrays import ExtensionArray
+from pandas.tests.test_common import (
+    DummyArray as _DummyArray,
```
Comment (mroeschke) [inline pandas/tests/extension/test_common.py:10]: Kinda getting lost in the renaming, where are `DummyArray` and `DummyDtype` defined here?

Comment (mroeschke) [reply pandas/tests/extension/test_common.py:10]: Oh nevermind, should have kept scrolling

File: pandas/core/arrays/base.py [hunk 2]
```diff
@@ -236,6 +239,7 @@ class ExtensionArray:
     # ------------------------------------------------------------------------
 
     @classmethod
+    @abstractmethod
```
Comment (mroeschke) [inline pandas/core/arrays/base.py:242]: This might be a fairly large change since EA authors will now need to actually make sure their unused methods are at least defined?

Comment (twoertwein) [reply pandas/core/arrays/base.py:242]: Can make them non-abstract and raise `NotImplementedError`. Are there more classes that should rather not be abstract?

File: pandas/tests/extension/test_common.py (hunk 1 above)
Comment (mroeschke) [reply pandas/tests/extension/test_common.py:10]: I think these are fine where they are. It would help if it was possible when subclassing just to give them a small naming difference like `ThisTestDummyArray(DummyArray)` instead of just `as _DummyArray`

File: pandas/core/arrays/base.py (hunk 2 above)
Comment (mroeschke) [reply pandas/core/arrays/base.py:242]: > Can make them non-abstract and raise NotImplementedError

Yeah I think this would be better

> Are there more classes that should rather not be abstract?

IMO anything that is in the public API would be better to raise a `NotImplementedError`

File: pandas/tests/extension/test_common.py (hunk 1 above)
Comment (twoertwein) [reply pandas/tests/extension/test_common.py:10]: This will hopefully be simpler when ExtensionArray/Dtype are not abstract anymore.

Comment (twoertwein) [reply pandas/tests/extension/test_common.py]: Almost no tests changed after not making ExtensionArray/Dtype abstract.

File: pandas/core/arrays/base.py (hunk 2 above)
Comment (twoertwein) [reply pandas/core/arrays/base.py]: ExtensionArray/Dtype are no longer abstract.

**Comment by twoertwein** [comment]
I finally setup python 3.8 and ran `asv continuous -f 1.1 -E virtualenv upstream/main HEAD`. Stupid question, how do I know whether there were/were no significant changes? It says neither of it at the bottom of the output.

@mroeschke @jbrockmendel

**Comment by twoertwein** [comment]
Happy to rebase occasionally - let me know if there is something else needed for this PR.

**Comment by twoertwein** [comment]
Would be great to get this deprecation in for 2.0 @mroeschke

**Comment by mroeschke** [comment]
It looks fairly good. Just noting that ideally we want to remove all the old 1.x deprecations before introducing new ones

**Comment by twoertwein** [comment]
> It looks fairly good. Just noting that ideally we want to remove all the old 1.x deprecations before introducing new ones

Are now all the 1.x deprecations removed? Rebased it earlier today.

**Comment by simonjayhawkins** [comment]
> Would be great to get this deprecation in for 2.0 @mroeschke

now that the rc is cut, aiming for 2.1?

**Comment by mroeschke** [comment]
Yeah 2.1 would be good.

**Comment by twoertwein** [comment]
After rebasing mypy reported new errors:

> pandas/core/series.py:1984: error: Cannot instantiate abstract class "SeriesGroupBy" with abstract attribute "_indexed_output_to_ndframe"  [abstract]
> pandas/core/groupby/groupby.py:4240: error: Can only assign concrete classes to a variable of type "Type[GroupBy[Any]]"  [misc]
> pandas/core/groupby/generic.py:1811: error: Cannot instantiate abstract class "SeriesGroupBy" with abstract attribute "_indexed_output_to_ndframe"  [abstract]
> pandas/core/groupby/generic.py:1862: error: Cannot instantiate abstract class "SeriesGroupBy" with abstract attribute "_indexed_output_to_ndframe"  [abstract]

So I remove `@abstractmethod`  from `SeriesGroupBy._indexed_output_to_ndframe` and instead raise inside the method.

**Comment by jbrockmendel** [comment]
_indexed_output_to_ndframe is no longer needed for SGB, can be removed and only exist on DFGB

**Comment by twoertwein** [comment]
The ASV Benchmark test seems to have failed - is there a summary of the 11k-line output?

**Comment by mroeschke** [comment]
Thinking aloud, it might be best to do this apart of 3.0 as a "breaking change without deprecation

**Comment by twoertwein** [comment]
I opened a new pull request #48913 to keep the commit history in this PR intact (rebasing a squashed PR is easier)
