### ISSUE TITLE
ENH: to_latex(): add posibility to define the latex environment (instead of table)

### ISSUE THREAD

**Issue by horror-vacui** [pandas-dev/pandas#37443]
#### Is your feature request related to a problem?

I wish pandas's to_latex() function could create table* environment instead of table for wide tables. The generated table sometimes does not fit into one column of a two column document. 

#### Describe the solution you'd like

A parameter where one can define the name of the environment. E.g. `df.to_latex(env="foobar*")` to generate: `\begin{foobar*} table stuff here \end{foobar*}`.

#### API breaking implications

One more parameter.

#### Describe alternatives you've considered

Write a code, which replaces begin{table} and end{table} to the desired environment. (table* in most of the cases)

**Comment by bashtage** [comment]
Why not just `df.to_latex().replace("{table}","{table*}")`?  Since you aren't proposing fundamentally changing the rendering of the table, it seems like there is not a strong case for expanding the API.

**Comment by horror-vacui** [comment]
> Why not just `df.to_latex().replace("{table}","{table*}")`? Since you aren't proposing fundamentally changing the rendering of the table, it seems like there is not a strong case for expanding the API.

I would be happy to use something like, but the snippet you wrote, does not work with the latest release (1.1.3).
```
Traceback (most recent call last):
  File "soa.py", line 236, in <module>
    column_format="cccccccccccccc"
AttributeError: 'NoneType' object has no attribute 'replace'

```
for 
```
df_table.to_latex(
            buf=tex_out,
            index=False,
            caption="Comparison with the State of the Art",
            label="tab:soa",
            na_rep="---",
            escape=False,
            bold_rows=True,
            column_format="cccccccccccccc"
            ).replace("{table}","{table*}")
```

**Comment by bashtage** [comment]
You need to not pass buf to get a string, which you can then call `replace` on.

```
buf.write(
    df_table.to_latex(
        index=False,
        caption="Comparison with the State of the Art",
        label="tab:soa",
        na_rep="---",
        escape=False,
        bold_rows=True,
        column_format="cccccccccccccc",
    ).replace("{table}", "{table*}")
)

```

**Comment by Kreijstal** [comment]
I would like to have this functionality, you don't necessarily need a tabular envirionment, it could be a matrix, a pmatrix, or some other environment.

**Comment by Kreijstal** [comment]
@jreback there is still no option to allow no environment at all, there are only 2 environments allowed?
