### ISSUE TITLE
BUILD: Pandas 1.2.5 with Python 3.10 on Win10

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [pandas-dev/pandas#45499]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Windows-10-10.0.19043-SP0

### Installation Method

pip install

### pandas Version

1.2.5

### Python Version

Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32

### Installation Logs

<details>

```
C:\Users\buhtzch>py -3 -m pip install pandas==1.2.5
Defaulting to user installation because normal site-packages is not writeable
Collecting pandas==1.2.5
  Using cached pandas-1.2.5.tar.gz (5.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=1.16.5
  Using cached numpy-1.22.1-cp310-cp310-win_amd64.whl (14.7 MB)
Requirement already satisfied: pytz>=2017.3 in c:\users\buhtzch\appdata\roaming\python\python310\site-packages (from pandas==1.2.5) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\buhtzch\appdata\roaming\python\python310\site-packages (from pandas==1.2.5) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\buhtzch\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.7.3->pandas==1.2.5) (1.16.0)
Building wheels for collected packages: pandas
  Building wheel for pandas (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python310\python.exe' 'C:\Users\buhtzch\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\buhtzch\AppData\Local\Temp\tmp6zq6o27s'
       cwd: C:\Users\buhtzch\AppData\Local\Temp\pip-install-3kasbtuo\pandas_5fd05fd68b3648929028cb428ca10cbb
  Complete output (1572 lines):
  setup.py:44: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _CYTHON_INSTALLED = _CYTHON_VERSION >= LooseVersion(min_cython_ver)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.10
  creating build\lib.win-amd64-3.10\pandas

<snipped>

  "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DNPY_NO_DEPRECATED_API=0 -I.\pandas\_libs\tslibs -IC:\Users\buhtzch\AppData\Local\Temp\pip-build-env-gjbh1he0\overlay\Lib\site-packages\numpy\core\include "-IC:\Program Files\Python310\include" "-IC:\Program Files\Python310\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcpandas\_libs/missing.c /Fobuild\temp.win-amd64-3.10\Release\pandas\_libs/missing.obj
  missing.c
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Program Files\Python310\libs" "/LIBPATH:C:\Program Files\Python310" "/LIBPATH:C:\Program Files\Python310\PCbuild\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" /EXPORT:PyInit_missing build\temp.win-amd64-3.10\Release\pandas\_libs/missing.obj /OUT:build\lib.win-amd64-3.10\pandas\_libs\missing.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.10\Release\pandas\_libs\missing.cp310-win_amd64.lib
     Bibliothek "build\temp.win-amd64-3.10\Release\pandas\_libs\missing.cp310-win_amd64.lib" und Objekt "build\temp.win-amd64-3.10\Release\pandas\_libs\missing.cp310-win_amd64.exp" werden erstellt.
  Code wird generiert.
  Codegenerierung ist abgeschlossen.
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DNPY_NO_DEPRECATED_API=0 -I.\pandas\_libs -Ipandas/_libs/src/klib -Ipandas/_libs/src -IC:\Users\buhtzch\AppData\Local\Temp\pip-build-env-gjbh1he0\overlay\Lib\site-packages\numpy\core\include "-IC:\Program Files\Python310\include" "-IC:\Program Files\Python310\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcpandas/_libs/src/parser/io.c /Fobuild\temp.win-amd64-3.10\Release\pandas/_libs/src/parser/io.obj
  io.c
  pandas/_libs/src/klib\khash.h(705): warning C4090: "Funktion": Unterschiedliche "const"-Qualifizierer
  pandas/_libs/src/parser/io.c(139): error C2065: "ssize_t": nichtdeklarierter Bezeichner
  pandas/_libs/src/parser/io.c(139): error C2146: Syntaxfehler: Fehlendes ";" vor Bezeichner "rv"
  pandas/_libs/src/parser/io.c(139): error C2065: "rv": nichtdeklarierter Bezeichner
  pandas/_libs/src/parser/io.c(145): error C2065: "rv": nichtdeklarierter Bezeichner
  pandas/_libs/src/parser/io.c(145): warning C4267: "Funktion": Konvertierung von "size_t" nach "unsigned int", Datenverlust m”glich
  pandas/_libs/src/parser/io.c(146): error C2065: "rv": nichtdeklarierter Bezeichner
  pandas/_libs/src/parser/io.c(157): error C2065: "rv": nichtdeklarierter Bezeichner
  pandas/_libs/src/parser/io.c(158): error C2065: "rv": nichtdeklarierter Bezeichner
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
```

</details>

### Comments
Because of my research project I am pinned to pandas Version 1.2.5.
The MS Build Tools are installed as you can see.
May it help to down grade to Python 3.9?

Maybe this is related to https://github.com/pandas-dev/pandas/issues/43969

**Comment by twoertwein** [comment]
Pandas 1.4.0 will be the first release with python 3.10 support. Pandas 1.2.5 should work with python 3.9 (wheels are on [pypi](https://pypi.org/project/pandas/1.2.5/#files))

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Then please take this as a bug report. You should mark the pandas 1.2.5 with a <= Python3.9* rule. This costs hours to break down the problem.

**Comment by imba-tjd** [comment]
For now there is a `pandas-1.4.0-cp310-cp310-win_amd64.whl` but there isn't a `pandas-1.4.0-cp310-cp310-win32.whl`. Is this expected?

**Comment by jreback** [comment]
32 bit windows wheels are not supported in python numpy or pandas any longer

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Maybe a bit late but I can confirm that `pandas==1.2.5` works with Python 3.9.10.

**Comment by imba-tjd** [comment]
numpy-1.22.3-cp310-cp310-win32.whl is available officially. According to https://stackoverflow.com/questions/69805894/will-numpy-wheels-for-python-3-10-32-bits-be-available, it was due to GitHub Actions not having 32bit Python on WinServer 2022. But they have added it back.
