### ISSUE TITLE
DOC: applying elementwise functions part

### ISSUE THREAD

**Issue by theangkko** [pandas-dev/pandas#55808]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#applying-elementwise-functions

<img width="866" alt="image" src="https://github.com/pandas-dev/pandas/assets/75212211/50422532-49c8-4222-9625-c7895d4a8ef2">

### Documentation problem

df4.map(f)

### Suggested fix for documentation

df4.applymap(f)

__________________________
If I use the "df4.map(f) " as per document,  I got the error message like 'DataFrame' object has no attribute 'map'.

I apply with - df4.applymap(f) - then I got the right result.

**Comment by samukweku** [comment]
What pandas version are you on? I think the map function should work with 2.1

**Comment by theangkko** [comment]
I am so sorry! It would be my FAULT

I tested again my laptop in version 2.0.2 and 2.1.2.  map() function works on ver 2.1.2.

<img width="255" alt="image" src="https://github.com/pandas-dev/pandas/assets/75212211/0ca2ca80-faa7-46d4-a11c-bc32a8220954">

I will close this issue and I will recheck my another environment or re-install pandas.
Thanks
