### ISSUE TITLE
No Python 3.13 wheels available in scientific-python-nightly-wheels

### ISSUE THREAD

**Issue by lesteve** [pandas-dev/pandas#59817]
Python 3.13 wheels have been failing for ~5 days see [build logs](https://github.com/pandas-dev/pandas/actions/workflows/wheels.yml?query=branch%3Amain+event%3Aschedule) and because of this, there is no Python 3.13 pandas wheel in [scientific-python-nightly-wheels](https://anaconda.org/scientific-python-nightly-wheels/pandas/files). We noticed this in scikit-learn where we are testing against pandas dev for Python 3.13 free-threaded https://github.com/scikit-learn/scikit-learn/issues/29852#issuecomment-2352255945.

The errors does not seem too hard to fix: `np._get_promotion_state` does not exist in numpy-dev and has been removed in https://github.com/numpy/numpy/pull/27156. Note that numpy 2.1.1 has Python 3.13 wheels and still has `np._get_promotion_state` so one option would be to switch to released numpy.

The error from [build log](https://github.com/pandas-dev/pandas/actions/runs/10877117924/job/30178019629#step:7:3864)
```
==================================== ERRORS ====================================
  ____________ ERROR collecting tests/series/indexing/test_setitem.py ____________
  ../venv/lib/python3.13/site-packages/pandas/tests/series/indexing/test_setitem.py:1449: in <module>
      or (np_version_gte1p24 and np._get_promotion_state() != "weak")
  ../venv/lib/python3.13/site-packages/numpy/__init__.py:414: in __getattr__
      raise AttributeError("module {!r} has no attribute "
  E   AttributeError: module 'numpy' has no attribute '_get_promotion_state'
  ____________ ERROR collecting tests/series/indexing/test_setitem.py ____________
  ../venv/lib/python3.13/site-packages/pandas/tests/series/indexing/test_setitem.py:1449: in <module>
      or (np_version_gte1p24 and np._get_promotion_state() != "weak")
  ../venv/lib/python3.13/site-packages/numpy/__init__.py:414: in __getattr__
      raise AttributeError("module {!r} has no attribute "
  E   AttributeError: module 'numpy' has no attribute '_get_promotion_state'
```

**Comment by jorisvandenbossche** [comment]
Thanks for noting! @lysnikolaou is fixing the actual test failure in https://github.com/pandas-dev/pandas/pull/59818, but indeed we also can stop building/testing our python 3.13 wheels with numpy nightly, so updating that in https://github.com/pandas-dev/pandas/pull/59819
