### ISSUE TITLE
BUG:  visit_Constant() got an unexpected keyword argument 'side'

### ISSUE THREAD

**Issue by yutiansut** [pandas-dev/pandas#36565]
- [ ] I have checked that this issue has not already been reported.

- [ x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

this is a simple example for me to show the error
```python
# Your code here


import pandas as pd

p = pd.DataFrame([[1,2,3],[2,3,4]], columns=['a','b','c'] )
p.query('a<1.2 and a>1')
```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]
in the code of  [code](https://github.com/pandas-dev/pandas/blob/master/pandas/core/computation/expr.py#L442)
```python
    def _maybe_transform_eq_ne(self, node, left=None, right=None):
        if left is None:
            left = self.visit(node.left, side="left")
        if right is None:
            right = self.visit(node.right, side="right")
        op, op_class, left, right = self._rewrite_membership_op(node, left, right)
        return op, op_class, left, right
```
there is side kwargs, however, when call the ```self.visit``` methods,  it tells 
```
TypeError: visit_Constant() got an unexpected keyword argument 'side'
```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-115-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 5.4.3
pip: 20.1.1
setuptools: 49.2.0.post20200714
Cython: 0.29.21
numpy: 1.18.5
scipy: 1.5.0
pyarrow: None
xarray: None
IPython: 7.16.1
sphinx: 3.1.2
patsy: 0.5.1
dateutil: 2.8.1
pytz: 2020.1
blosc: None
bottleneck: 1.3.2
tables: 3.6.1
numexpr: 2.7.1
feather: None
matplotlib: 3.2.2
openpyxl: 3.0.4
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.2.9
lxml.etree: 4.5.2
bs4: 4.9.1
html5lib: 1.1
sqlalchemy: 1.3.18
pymysql: 0.10.0
psycopg2: None
jinja2: 2.11.2
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

**Comment by jreback** [comment]
i don't think 3.8 is supported at all in 0.24 - if it works its happenstance 

you need to update to something more recent

**Comment by jreback** [comment]
if this doesn't work in more recent version (1.1.2) is latest

ping and we can reopen
