### PR TITLE
Fix type annotation in pandas.compat

### LINKED ISSUE #26251: Fix Type Annotation in  pandas.compat
Part of #25882

Type annotations for the following file need to be corrected to remove **pandas.compat** from the mypy blacklist. 

Mypy throws the following error:
```sh
pandas/compat/__init__.py:81: error: Module has no attribute "re"
```

PR to follow.

### PR DESCRIPTION
**Pull request by gwrome**
- [X] closes #26251
- [X] tests passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

File: pandas/compat/__init__.py [hunk 1]
```diff
@@ -74,11 +74,9 @@ def raise_with_traceback(exc, traceback=Ellipsis):
     raise exc.with_traceback(traceback)
 
 
-# In Python 3.7, the private re._pattern_type is removed.
-# Python 3.5+ have typing.re.Pattern
```
Comment (gwrome) [inline pandas/compat/__init__.py]: I removed these comments because they're misleading. `typing.re.Pattern` is available in 3.5-3.7. It's been removed from the documentation as of 3.6, but it continues to be available. As of 3.6, the documented method is to use `typing.Pattern`, which also works in 3.5. I've adopted that pattern in this PR, which corrected the mypy error

File: pandas/compat/__init__.py [hunk 2]
```diff
@@ -74,11 +74,9 @@ def raise_with_traceback(exc, traceback=Ellipsis):
...
 if PY36:
-    import typing
-    re_type = typing.re.Pattern
+    from typing import Pattern, Type
```
Comment (jreback) [inline pandas/compat/__init__.py]: do these exist in 3.5? can u move this import to the top?

Comment (WillAyd) [reply pandas/compat/__init__.py]: Type I think is from 3.5.2. We've used elsewhere so need to address at some point. Maybe vendoring, either dropping < 3.5.2 or vendoring that piece

Comment (WillAyd) [reply pandas/compat/__init__.py]: Ignoring my previous comment for a second would we even need the Py36 condition or can we import all from the same space across versions?

Comment (gwrome) [reply pandas/compat/__init__.py]: I've successfully tested `from typing import Pattern, Type` in 3.5.7, 3.6.8, and 3.7.3. I can't speak for anything before 3.5.7, but there's no problem importing after the most recent 3.5 micro version. I'll move the imports to the top and drop the else.

**Comment by jreback** [comment]
thanks!
