### ISSUE TITLE
BUG: Binary operations (__and__, __or__, etc.) do not take parameter `axis` and fail

### ISSUE THREAD

**Issue by YarShev** [pandas-dev/pandas#39519]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas as pd
import numpy as np
df = pd.DataFrame([1, 1])
a = np.array([0, 1])
df.__and__(a, axis=0)
TypeError: new_method() got an unexpected keyword argument 'axis'
```

#### Problem description

This worked in pandas 1.1.5

#### Expected Output

```python
df.__and__(a, axis=0)
   0
0  0
1  1
```

#### Output of ``pd.show_versions()``

<details>

pandas           : 1.2.1
numpy            : 1.19.5
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 51.1.2.post20210112
Cython           : None
pytest           : 6.2.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : 0.8.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.2
numexpr          : 2.7.2
odfpy            : None
openpyxl         : 3.0.6
pandas_gbq       : None
pyarrow          : 2.0.0
pyxlsb           : None
s3fs             : 0.5.2
scipy            : 1.6.0
sqlalchemy       : 1.3.22
tables           : 3.6.1
tabulate         : None
xarray           : 0.16.2
xlrd             : 2.0.1
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment]
first bad commit is 7f1c3b1c4804be4d818deeba8f598de63ca23e19 cc @jbrockmendel

**Comment by lithomas1** [comment]
xref #36796
cc @jbrockmendel @jreback

**Comment by simonjayhawkins** [comment]
> first bad commit is [7f1c3b1](https://github.com/pandas-dev/pandas/commit/7f1c3b1c4804be4d818deeba8f598de63ca23e19) cc @jbrockmendel

#36843

**Comment by simonjayhawkins** [comment]
It appears this was an intentional change https://github.com/pandas-dev/pandas/issues/36796#issuecomment-704664641

**Comment by simonjayhawkins** [comment]
@jorisvandenbossche potential discussion item for dev meeting tomorrow.

**Comment by jorisvandenbossche** [comment]
The dunder methods are not meant to call directly like that, so we shouldn't guarantee any stability here IMO

**Comment by jorisvandenbossche** [comment]
Alternative solution for when the right array operand is not exactly shape-aligned to avoid the axis:

Reshape (and potentially broadcast) the array so it automatically aligns on the index dimension (axis=0):

```
In [5]: df & a.reshape(-1, 1)
Out[5]: 
   0
0  0
1  1
```

You need to do the same when using ufuncs like `np.logical_and` (those also don't have an axis keyword, and need correctly shaped arrays to ensure shapes are matching / broadcasting is possible).

**Comment by jorisvandenbossche** [comment]
So give that it's a dunder method that shouldn't be called directly, and given that there are alternatives, I think it is fine to close this issue.

(note, we could still discuss separately if we want to add a "flex" method for those logical operations, like we have a `df.add(..)` method that is equivalent to `__add__` but with more flexibility and keywords)
