### ISSUE TITLE
build problem with cython 0.21.2

### ISSUE THREAD

**Issue by durack1** [pandas-dev/pandas#9591]
I've just tried to build pandas0.15.2 and hit the problem below:

```
pandas/parser.pyx:164:39: Expected ')', found '*'
building 'pandas.parser' extension
creating build/temp.linux-x86_64-2.7/pandas/src/parser
gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/2015-02-10/Externals/include -L/usr/local/uvcdat/2015-02-10/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipandas/src/klib -Ipandas/src -I/usr/local/uvcdat/latest/lib/python2.7/site-packages/numpy/core/include -I/usr/local/uvcdat/latest/include/python2.7 -c pandas/parser.c -o build/temp.linux-x86_64-2.7/pandas/parser.o
pandas/parser.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
error: command 'gcc' failed with exit status 1
[durack1@oceanonly pandas0.15.2]$ which python
/usr/local/uvcdat/2015-02-25/bin/python
[durack1@oceanonly pandas0.15.2]$ python
Python 2.7.9 (default, Feb 25 2015, 21:24:47)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cython
>>> cython.__version__
'0.21.2'
```

**Comment by jreback** [comment]
can you show ``pd.show_versions()``

builds fine on 0.21 (and 0.22.2) and haven't heard of any other issues.

how are you building?

**Comment by durack1** [comment]
Is there an import statement that I need before calling `pd.show_versions()`? As pandas is not installed I'm not sure I can prompt for this output?

I'm trying to install from the tarball using `python setup.py install --user`

**Comment by jreback** [comment]
hmm that should work (though never used the --user flag)

**Comment by durack1** [comment]
On redhat this builds into `~.local/` which is really helpful for systems you don't have admin privileges

**Comment by jreback** [comment]
ok

not sure what the issue here is 
but using conda is quite convenient for installation nowadays

**Comment by rockg** [comment]
Is that all that outputs for your error?  I reported a similar problem in #9563 and it was the same module although the error was a bit different.

**Comment by durack1** [comment]
Apologies for the delayed reply - this is the full output:
```
[~ pandas-0.15.2]$ python --version
Python 2.7.9
[~ pandas-0.15.2]$ python setup.py install --user
running install
running bdist_egg
running egg_info
writing requirements to pandas.egg-info/requires.txt
writing pandas.egg-info/PKG-INFO
writing top-level names to pandas.egg-info/top_level.txt
writing dependency_links to pandas.egg-info/dependency_links.txt
reading manifest file 'pandas.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.rst'
no previously-included directories found matching 'doc/build'
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '#*' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
writing manifest file 'pandas.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying pandas/version.py -> build/lib.linux-x86_64-2.7/pandas
running build_ext
skipping 'pandas/index.c' Cython extension (up-to-date)
skipping 'pandas/algos.c' Cython extension (up-to-date)
skipping 'pandas/lib.c' Cython extension (up-to-date)
skipping 'pandas/tslib.c' Cython extension (up-to-date)
cythoning pandas/parser.pyx to pandas/parser.c

Error compiling Cython file:
------------------------------------------------------------
...
        int header_end # header row end

        void *skipset
        int64_t skip_first_N_rows
        int skip_footer
        double (*converter)(const char *, char **, char, char, char, int)
                                      ^
------------------------------------------------------------

pandas/parser.pyx:164:39: Expected ')', found '*'
building 'pandas.parser' extension
gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/2015-02-10/Externals/include -L/usr/local/uvcdat/2015-02-10/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipandas/src/klib -Ipandas/src -I/usr/local/uvcdat/latest/lib/python2.7/site-packages/numpy/core/include -I/usr/local/uvcdat/latest/include/python2.7 -c pandas/parser.c -o build/temp.linux-x86_64-2.7/pandas/parser.o
pandas/parser.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
error: command 'gcc' failed with exit status 1
```

**Comment by jreback** [comment]
I would guess you are actually picking up an older version of cython
