### PR TITLE
Fix regression in .ix fallback with IntervalIndex

### LINKED ISSUE #27865: Cannot use .ix in IntervaIndex('pandas._libs.interval.IntervalTree' object has no attribute 'get_value')
#### Code Sample, a copy-pastable example if possible

```python
x = pd.Series([-2.801298, -2.882724, -3.007899, -2.704554, -3.398761, -2.805034, -2.87554, -2.805034, -2.886459, -2.471618])
y= pd.Series([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
init_cut = pd.qcut(x, 5, duplicates='drop')
retbin = pd.Series(init_cut.values.categories).sort_values()
retbin.iloc[0] = pd.Interval(-np.inf, retbin.iloc[0].right)
retbin.iloc[-1] = pd.Interval(retbin.iloc[-1].left, np.inf)
init_cut = pd.cut(x, pd.IntervalIndex(retbin))
init_cut = init_cut.astype(object)
bin_df = pd.crosstab(index=init_cut, columns=y)
bin_df = bin_df.reindex(retbin)
bin_df = bin_df.sort_index()
bin_df = bin_df.fillna(0.0)
bin_df['nbin'] = np.nan
```

#### Problem description
bin_df = 
col_0             0  nbin
(-inf, -2.911]    2   NaN
(-2.911, -2.878]  2   NaN
(-2.878, -2.805]  3   NaN
(-2.805, -2.782]  1   NaN
(-2.782, inf]     2   NaN

if I use bin_df.ix[0:2,0], I got an error like:

```pytb
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-1ae8ba69565c>", line 1, in <module>
    bin_df.ix[0:1,'nbin']
  File "D:\PyTest\venv\lib\site-packages\pandas\core\indexing.py", line 125, in __getitem__
    values = self.obj._get_value(*key)
  File "D:\PyTest\venv\lib\site-packages\pandas\core\frame.py", line 2827, in _get_value
    return engine.get_value(series._values, index)
AttributeError: 'pandas._libs.interval.IntervalTree' object has no attribute 'get_value'
```

the version is 0.25.0
but it works well in 0.24.x

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
closes #27865

cc @jbrockmendel this is another one from limiting the catched exceptions in https://github.com/pandas-dev/pandas/pull/27223/files#diff-7489e290a23303c4db4f803011ecaf8eR121. But also this time it's again rather a bug in the code that raises this error.

For some reason, `DataFrame._get_value` for a DataFrame with an IntervalIndex raises an AttributeError. That's a bug in itself which should be solved (and probably is the cause of more bugs in other places where `_get_value` is used, eg in `.at`). But will open a separate issue for that.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Opened https://github.com/pandas-dev/pandas/issues/27927

**Comment by jreback** [comment]
really? we haven't patched .ix in many releases. And we are removing it.

**Comment by jbrockmendel** [comment]
@jorisvandenbossche you work on windows right?  can you reproduce the azure failure?

**Comment by jorisvandenbossche** [comment]
No, sorry, no windows :) (linux)

**Comment by jorisvandenbossche** [comment]
> really? we haven't patched .ix in many releases. And we are removing it.

Then we maybe also shouldn't have tried to clean up the code .. ;)

Anyway, this is just for 0.25.1, in master afterwards we can remove it again (when removing ix). 
If the idea is that people can upgrade to 0.25, see all the warnings to fix them, to then be able to upgrade to 1.0, then the their code needs to work to be able to do that.

**Comment by jbrockmendel** [comment]
Do I understand correctly: there is a bug in IntervalTree and fixing that would make this fix unnecessary?

**Comment by TomAugspurger** [comment]
Yep. But I think that catching AttributeError here is a bit more conservative for the backport.

**Comment by jorisvandenbossche** [comment]
Yes, I opened  #27927 for that (the bug appears in other places as well, but there it was already failing before, so not a regression)

**Comment by jorisvandenbossche** [comment]
Any objections to merge this?

**Comment by TomAugspurger** [comment]
I think we're good. I had to restart the CI earlier for a failed build from the flaky test.

**Comment by jorisvandenbossche** [comment]
@MeeseeksDev backport to 0.25.x
