### ISSUE TITLE
Pandas not working in Anaconda3 4.2. Not able to update also

### ISSUE THREAD

**Issue by puneethmishra** [pandas-dev/pandas#15250]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-d6ac987968b6> in <module>()
----> 1 import pandas

D:\Anaconda3-4.2\lib\site-packages\pandas\__init__.py in <module>()
     20 
     21 # numpy compat
---> 22 from pandas.compat.numpy import *
     23 
     24 try:

D:\Anaconda3-4.2\lib\site-packages\pandas\compat\numpy\__init__.py in <module>()
      4 import numpy as np
      5 from distutils.version import LooseVersion
----> 6 from pandas.compat import string_types, string_and_binary_types
      7 
      8 # turn off all numpy warnings

ImportError: cannot import name 'string_types'

**Comment by jreback** [comment]
well you haven't provided what you did to install nor what is you are on (windows by your paths)

did you try:

conda install pandas

**Comment by puneethmishra** [comment]
$ conda install pandas
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment D:\Anaconda3-4.2:

The following packages will be UPDATED:

    pandas: 0.18.1-np111py35_0 --> 0.19.2-np111py35_1

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : D:\Anaconda3-4.2  (writable)
    default environment : D:\Anaconda3-4.2
       envs directories : D:\Anaconda3-4.2\envs
          package cache : D:\Anaconda3-4.2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.5.2 Windows/7 Windows/6.1.7601



`$ D:\Anaconda3-4.2\Scripts\conda-script.py install pandas`




    Traceback (most recent call last):
      File "D:\Anaconda3-4.2\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\Anaconda3-4.2\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "D:\Anaconda3-4.2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "D:\Anaconda3-4.2\lib\site-packages\conda\cli\install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "D:\Anaconda3-4.2\lib\site-packages\conda\plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "D:\Anaconda3-4.2\lib\site-packages\conda\instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "D:\Anaconda3-4.2\lib\site-packages\conda\instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "D:\Anaconda3-4.2\lib\site-packages\conda\core\link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "D:\Anaconda3-4.2\lib\site-packages\conda\core\link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "D:\Anaconda3-4.2\lib\site-packages\conda\gateways\disk\read.py", line 71, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "D:\Anaconda3-4.2\lib\site-packages\conda\gateways\disk\read.py", line 94, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Anaconda3-4.2\\pkgs\\pandas-0.19.2-np111py35_1\\info\\index.json'

**Comment by jreback** [comment]
i wouldn't say you have a broken installation

iirc you SO issue you did have permission issues

you can post on conda if you want but usually just uninstall Anaconda and reinstall to fix the brokeness

**Comment by puneethmishra** [comment]
I have tried uninstalling and reinstalling still doesn't help.
All the packages are getting installed fine, but there are issues only with pandas.

When i try pip to upgrade the package:
$ pip install --upgrade pandas
Collecting pandas
  Using cached pandas-0.19.2-cp35-cp35m-win_amd64.whl
Exception:
Traceback (most recent call last):
  File "D:\Anaconda3-4.2\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "D:\Anaconda3-4.2\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "D:\Anaconda3-4.2\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "D:\Anaconda3-4.2\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "D:\Anaconda3-4.2\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "D:\Anaconda3-4.2\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "D:\Anaconda3-4.2\lib\site-packages\pip\download.py", line 663, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "D:\Anaconda3-4.2\lib\site-packages\pip\utils\__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "D:\Anaconda3-4.2\lib\site-packages\pip\utils\__init__.py", line 499, in unzip_file
    fp = open(fn, 'wb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\463076\\AppData\\Local\\Temp\\pip-build-4h4myslf\\pandas\\pandas/io/tests/data/blank.xls'


Not sure why the path changes after pandas/io

Is that the cause , are some path not set correctly.

**Comment by jreback** [comment]
use pip with pandas inside of anaconda is not recommended

**Comment by puneethmishra** [comment]
What is the significance of this file:
No such file or directory: 'D:\\Anaconda3-4.2\\pkgs\\pandas-0.19.2-np111py35_1\\info\\index.json'
What could be the possible causes of this file being not created

**Comment by jreback** [comment]
that's meta data that conda uses 

again pls ask on the conda channel
