### PR TITLE
 ENH/TST: Add TestBaseArithmeticOps tests for ArrowExtensionArray #47601 

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

Generally the xfails correspond to:

* pyarrow < 2 not having the *_checked ops
* pyarrow < 8 not supporting arithmetic with some temporal types
* pyarrow not having mod/rmod compute functions
* `1**pandas.NA == 1` while `1**pyarrow.NA == NULL`

### CODE REVIEW

File: pandas/core/arrays/arrow/array.py [hunk 1]
```diff
@@ -57,6 +57,34 @@
...
+    }
+
+    ARROW_ARITHMETIC_FUNCS = {
+        "add": pc.add_checked,
+        "radd": lambda x, y: pc.add(y, x),
+        "sub": pc.subtract_checked,
+        "rsub": lambda x, y: pc.subtract_checked(y, x),
+        "mul": pc.multiply_checked,
+        "rmul": lambda x, y: pc.multiply_checked(y, x),
+        "truediv": NotImplemented,  # pc.divide_checked,
```
Comment (mroeschke) [inline pandas/core/arrays/arrow/array.py:76]: @jorisvandenbossche is it expected for `divide_checked` to have different semantics for integers?

```
In [1]: import pyarrow as pa

In [2]: 5 / 2
Out[2]: 2.5

In [3]: np.int64(5) / 2
Out[3]: 2.5

In [4]: pa.compute.divide_checked(pa.scalar(5), 2)
Out[4]: <pyarrow.Int64Scalar: 2>

In [5]: 5. / 2
Out[5]: 2.5

In [6]: np.float64(5) / 2
Out[6]: 2.5

In [7]: pa.compute.divide_checked(pa.scalar(5.), 2)
Out[7]: <pyarrow.DoubleScalar: 2.5>

In [8]: pa.__version__
Out[8]: '7.0.0
```

Comment (jorisvandenbossche) [reply pandas/core/arrays/arrow/array.py:76]: The division kernels are only implemented for int input -> int output, float input -> float output, etc. Since in our case division with integers always results in floats, I think we can emulate that with casting the integer input to float first (that's for example also what the arrow R dplyr bindings do).

File: pandas/tests/arrays/string_/test_string.py [hunk 2]
```diff
@@ -101,7 +101,7 @@ def test_add(dtype, request):
             "unsupported operand type(s) for +: 'ArrowStringArray' and "
             "'ArrowStringArray'"
         )
-        mark = pytest.mark.xfail(raises=TypeError, reason=reason)
+        mark = pytest.mark.xfail(raises=NotImplementedError, reason=reason)
```
Comment (jorisvandenbossche) [inline pandas/tests/arrays/string_/test_string.py:104]: BTW (not necessarily for this PR), but `+` for strings is actually implemented in Arrow, but under the "join" name (like str.join), so this could be emulated using `pc.binary_join_element_wise(left, right, "")` (the last empty string is to not use a separator)

File: pandas/core/arrays/arrow/array.py (hunk 1 above)
Comment (mroeschke) [reply pandas/core/arrays/arrow/array.py:89]: Thanks for confirming the behavior!

I think this touches upon a larger philosophical question for "using arrow in pandas"

1. Should pandas make arrow follow pandas' conventions? (e.g. pandas casts such that int / int -> float)
2. Should pandas just be an interface for arrow to propagate its conventions? (e.g. int / int -> int)

Probably should be discussed with a larger audience, but personally I've been leaning 2.

Comment (jorisvandenbossche) [reply pandas/core/arrays/arrow/array.py:86]: In practice I suppose it will be something in the middle? 

We certainly shouldn't blindly follow existing pandas behaviours, but I think we will also certainly need to add some user convenience layer on top of Arrow (now, in this specific case, it's of course more an API behaviour choice rather than a user convenience issue).

(Arrow needs to cater for many different bindings and use cases (databases, dataframe libraries), so sometimes will also have more options / different defaults / different names than what a Python user expects). 

But indeed something interesting to discuss (both more broadly in general terms, and we will probably still often need some discussion on a case by case basis).

File: pandas/tests/extension/test_arrow.py [hunk 3]
```diff
@@ -1491,6 +1516,325 @@ def test_where_series(self, data, na_value, as_frame, request, using_array_manag
...
+                )
+            )
+        super().test_add_series_with_extension_array(data)
+
+
+class TestBaseComparisonOps(base.BaseComparisonOpsTests):
+    def assert_series_equal(self, left, right, *args, **kwargs):
+        # Series.combine for "expected" retains bool[pyarrow] dtype
+        # While "result" return "boolean" dtype
+        right = pd.Series(right._values.to_numpy(), dtype="boolean")
```
Comment (jreback) [inline pandas/tests/extension/test_arrow.py:1794]: this is not great

**Review by jreback — APPROVED** [review]
small comment, but lgtm

File: pandas/core/arrays/arrow/array.py [hunk 4]
```diff
@@ -57,6 +57,76 @@
...
+        if pa_version_under2p0
+        else lambda x, y: floordiv_compat(x, y),
+        "rfloordiv": NotImplemented
+        if pa_version_under2p0
+        else lambda x, y: floordiv_compat(y, x),
+        "mod": NotImplemented,
+        "rmod": NotImplemented,
+        "divmod": NotImplemented,
+        "rdivmod": NotImplemented,
+        "pow": NotImplemented if pa_version_under2p0 else pc.power_checked,
```
Comment (simonjayhawkins) [inline pandas/core/arrays/arrow/array.py:124]: failing with pyarrow 2.0.0 

```python
ImportError while loading conftest '/home/simon/pandas/pandas/conftest.py'.
pandas/__init__.py:48: in <module>
    from pandas.core.api import (
pandas/core/api.py:27: in <module>
    from pandas.core.arrays import Categorical
pandas/core/arrays/__init__.py:20: in <module>
    from pandas.core.arrays.string_arrow import ArrowStringArray
pandas/core/arrays/string_arrow.py:37: in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
pandas/core/arrays/arrow/__init__.py:1: in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
pandas/core/arrays/arrow/array.py:124: in <module>
    "pow": NotImplemented if pa_version_under2p0 else pc.power_checked,
E   AttributeError: module 'pyarrow.compute' has no attribute 'power_checked'
```

File: pandas/tests/extension/test_arrow.py (hunk 3 above)
Comment (mroeschke) [reply pandas/tests/extension/test_arrow.py:1794]: Yeah using `Series.combine` to generate `expected` for these ExtensionArray tests doesn't always compare nicely with pyarrow. 

I wouldn't say there's a bug in `Series.combine` or this implementation, just a consequence of `Series.combine` using Python comparisons semantics and not necessarily Arrow comparison semantics

Comment (jorisvandenbossche) [reply pandas/tests/extension/test_arrow.py:1794]: In general I would maybe also not do too much effort in trying to fully implement all those tests (too late probably) following the base extension tests exactly. As those need to be written in a generic way, that also makes them not very robust (eg the `combine()` method) / often awkward to write. 
It might make sense to write a set of custom, more targeted set of tests for a group of dtypes like the arrow dtypes (for certain operations)

File: pandas/core/arrays/arrow/array.py (hunk 4 above)
Comment (jorisvandenbossche) [reply pandas/core/arrays/arrow/array.py:124]: I merged @mroeschke's follow up PR (https://github.com/pandas-dev/pandas/pull/47752), but I am now wondering: we don't have CI builds with pyarrow 2.0 to catch this?

Comment (mroeschke) [reply pandas/core/arrays/arrow/array.py:124]: We don't, only testing 1.01 (min), 5, 6, 7. IIRC pyarrow version 2 or 3 were causing the CI to time out around the read_csv tests so that's why 2 or 3 weren't included https://github.com/pandas-dev/pandas/issues/43650
